// SANDRA'S MOODBOARD COLLECTIONS
// 10 Collections with 200+ flatlays each for perfect design balance
// Last Updated: 2025-07-07

export interface MoodboardCollection {
  id: string;
  name: string;
  description: string;
  theme: string;
  coverImage: string;
  images: string[];
}

export const MoodboardCollections: MoodboardCollection[] = [
  {
    id: 'luxury-minimal',
    name: 'Luxury Minimal',
    description: 'Clean lines, neutral tones, sophisticated layouts',
    theme: 'luxury',
    coverImage: '', // Will be first image in collection
    images: [
      // Collection 1: Luxury Minimal (200+ URLs to be added)
      // Placeholder for now - Sandra will provide PostImg URLs
    ]
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial Magazine', 
    description: 'Magazine-style layouts with typography focus',
    theme: 'editorial',
    coverImage: '',
    images: [
      // Collection 2: Editorial Magazine
    ]
  },
  {
    id: 'luxury-minimal-new',
    name: 'Luxury Minimal Studio',
    description: 'Clean lines, neutral tones, sophisticated workspace layouts - perfect for SSELFIE STUDIO themes',
    theme: 'luxury',
    coverImage: 'https://i.postimg.cc/QtnSw23T/1.png',
    images: [
      'https://i.postimg.cc/QtnSw23T/1.png',
      'https://i.postimg.cc/FKrM4X2W/10.png',
      'https://i.postimg.cc/HnMYyCW0/100.png',
      'https://i.postimg.cc/tTwRJgbC/101.png',
      'https://i.postimg.cc/c1t4jf7K/102.png',
      'https://i.postimg.cc/TY8YXhQt/103.png',
      'https://i.postimg.cc/Ghk33r5d/104.png',
      'https://i.postimg.cc/bwpysM7b/105.png',
      'https://i.postimg.cc/6pc9RcKP/106.png',
      'https://i.postimg.cc/QMMjq7xd/107.png',
      'https://i.postimg.cc/TPHfNPpq/108.png',
      'https://i.postimg.cc/LXYRcMPd/109.png',
      'https://i.postimg.cc/9fLvXN2W/11.png',
      'https://i.postimg.cc/J7XMKMmZ/110.png',
      'https://i.postimg.cc/Y0Q7Sf8b/111.png',
      'https://i.postimg.cc/4NTZSqNM/112.png',
      'https://i.postimg.cc/TYqGM0KP/113.png',
      'https://i.postimg.cc/dVsFqCCj/114.png',
      'https://i.postimg.cc/P5SjNqzs/115.png',
      'https://i.postimg.cc/LshMPMNq/116.png',
      'https://i.postimg.cc/CKtpH6Qc/117.png',
      'https://i.postimg.cc/HxyDS9Gd/118.png',
      'https://i.postimg.cc/T1v8B5Gm/119.png',
      'https://i.postimg.cc/wv3n1cxD/12.png',
      'https://i.postimg.cc/vT7Ry8HK/120.png',
      'https://i.postimg.cc/Df13L6dc/121.png',
      'https://i.postimg.cc/8PH8nCYJ/122.png',
      'https://i.postimg.cc/DyFkgGx3/123.png',
      'https://i.postimg.cc/XYHR4z4n/124.png',
      'https://i.postimg.cc/bwwXXhX6/125.png',
      'https://i.postimg.cc/SKnwsfxC/126.png',
      'https://i.postimg.cc/YSTTmLvV/127.png',
      'https://i.postimg.cc/vB9k789m/128.png',
      'https://i.postimg.cc/8cmY3yZQ/129.png',
      'https://i.postimg.cc/63Sgn2Tg/13.png',
      'https://i.postimg.cc/hPK6xBGS/130.png',
      'https://i.postimg.cc/2jQgV6rc/131.png',
      'https://i.postimg.cc/WbSKwHD0/132.png',
      'https://i.postimg.cc/K8zWqDLw/133.png',
      'https://i.postimg.cc/wjGGSRQv/134.png',
      'https://i.postimg.cc/mr15RZmS/135.png',
      'https://i.postimg.cc/wvKbBKPY/136.png',
      'https://i.postimg.cc/ZRrsB7tB/137.png',
      'https://i.postimg.cc/ZnHfjWqJ/138.png',
      'https://i.postimg.cc/x8nxKvns/139.png',
      'https://i.postimg.cc/nrD5kFDz/14.png',
      'https://i.postimg.cc/c41kCBDC/140.png',
      'https://i.postimg.cc/gcHBGTH1/141.png',
      'https://i.postimg.cc/BnXhcQfG/142.png',
      'https://i.postimg.cc/yYfQZ35P/143.png',
      'https://i.postimg.cc/dVp5WPJZ/144.png',
      'https://i.postimg.cc/VNtDpGNG/145.png',
      'https://i.postimg.cc/B6GM0TLq/146.png',
      'https://i.postimg.cc/PxzKrCY1/147.png',
      'https://i.postimg.cc/rsVjdqN3/148.png',
      'https://i.postimg.cc/C5cNk9v1/149.png',
      'https://i.postimg.cc/59YZ13RV/15.png',
      'https://i.postimg.cc/QxMShxtW/150.png',
      'https://i.postimg.cc/fTgCLntq/151.png',
      'https://i.postimg.cc/FHdZkW0r/152.png',
      'https://i.postimg.cc/jSphHHhz/153.png',
      'https://i.postimg.cc/TwGqSTF1/154.png',
      'https://i.postimg.cc/vm5t34PC/155.png',
      'https://i.postimg.cc/W3n6cQcn/156.png',
      'https://i.postimg.cc/Vvk9fDYc/157.png',
      'https://i.postimg.cc/0jXYbDQK/158.png',
      'https://i.postimg.cc/jqMQg0Xq/159.png',
      'https://i.postimg.cc/3rszwvsD/16.png',
      'https://i.postimg.cc/vHD7Cqqr/160.png',
      'https://i.postimg.cc/GhNPRFVZ/161.png',
      'https://i.postimg.cc/FHLyHfQ1/162.png',
      'https://i.postimg.cc/0NG77Ljs/163.png',
      'https://i.postimg.cc/25N4bzzG/164.png',
      'https://i.postimg.cc/SsyCdDYz/165.png',
      'https://i.postimg.cc/SRP9y4TW/166.png',
      'https://i.postimg.cc/DwkW5Bty/167.png',
      'https://i.postimg.cc/wjX1rDp5/168.png',
      'https://i.postimg.cc/KYm1h4G6/169.png',
      'https://i.postimg.cc/wTDZRBz4/17.png',
      'https://i.postimg.cc/CxS8ScJr/170.png',
      'https://i.postimg.cc/13BqtDjm/171.png',
      'https://i.postimg.cc/VkKJ1mJ5/172.png',
      'https://i.postimg.cc/sfWGWkN0/173.png',
      'https://i.postimg.cc/66CTqd8k/174.png',
      'https://i.postimg.cc/3J7Nvdpd/175.png',
      'https://i.postimg.cc/T1xdg4KZ/176.png',
      'https://i.postimg.cc/0yj8YmN2/177.png',
      'https://i.postimg.cc/8P1kCxQv/178.png',
      'https://i.postimg.cc/mkVsM2fH/179.png',
      'https://i.postimg.cc/YCkV6wqr/18.png',
      'https://i.postimg.cc/Z5cQjDCr/19.png',
      'https://i.postimg.cc/vmh0L12X/2.png',
      'https://i.postimg.cc/DzwMNdXR/20.png',
      'https://i.postimg.cc/tgvMGZdJ/21.png',
      'https://i.postimg.cc/TwyHddQ9/22.png',
      'https://i.postimg.cc/x8Mxm6wN/23.png',
      'https://i.postimg.cc/ydwpWMbz/24.png',
      'https://i.postimg.cc/tCdvCmdL/25.png',
      'https://i.postimg.cc/3JQbhHGX/26.png',
      'https://i.postimg.cc/T2DHBPK2/27.png',
      'https://i.postimg.cc/Z5T79FV0/28.png',
      'https://i.postimg.cc/L8NyjYbD/29.png',
      'https://i.postimg.cc/gJ0NMYfp/3.png',
      'https://i.postimg.cc/HLn6zWGg/30.png',
      'https://i.postimg.cc/rpHQP6ct/31.png',
      'https://i.postimg.cc/tTV20rCv/32.png',
      'https://i.postimg.cc/ZntjJrWb/33.png',
      'https://i.postimg.cc/7h39hfzg/34.png',
      'https://i.postimg.cc/Y2YbbyPh/35.png',
      'https://i.postimg.cc/nc1Tt9px/36.png',
      'https://i.postimg.cc/3Jh96FM9/37.png',
      'https://i.postimg.cc/8zP4kkz6/38.png',
      'https://i.postimg.cc/DwjgSVSY/39.png',
      'https://i.postimg.cc/wMyFpwqb/4.png',
      'https://i.postimg.cc/BvRBCxcT/40.png',
      'https://i.postimg.cc/bJbHVs3K/41.png',
      'https://i.postimg.cc/C5sCY9y7/42.png',
      'https://i.postimg.cc/mks3vBnh/43.png',
      'https://i.postimg.cc/ncnYTV7P/44.png',
      'https://i.postimg.cc/wxXQhRtN/45.png',
      'https://i.postimg.cc/7Z618BK1/46.png',
      'https://i.postimg.cc/zXpwQmFX/47.png',
      'https://i.postimg.cc/VkVqYjhx/48.png',
      'https://i.postimg.cc/zBmThq8p/49.png',
      'https://i.postimg.cc/L4JM5RhG/5.png',
      'https://i.postimg.cc/NM1m7Z0t/50.png',
      'https://i.postimg.cc/hvcxCMJd/51.png',
      'https://i.postimg.cc/L5DPGff0/52.png',
      'https://i.postimg.cc/FFV0ftqg/53.png',
      'https://i.postimg.cc/SNQCCTb0/54.png',
      'https://i.postimg.cc/YqXg36tv/55.png',
      'https://i.postimg.cc/RZNtbW0X/56.png',
      'https://i.postimg.cc/MpNBkzMx/57.png',
      'https://i.postimg.cc/N0XHBZmX/58.png',
      'https://i.postimg.cc/50MF0pSR/59.png',
      'https://i.postimg.cc/44jRhM9y/6.png',
      'https://i.postimg.cc/Pxzv8Z6r/60.png',
      'https://i.postimg.cc/MH6M0T40/61.png',
      'https://i.postimg.cc/Pfy8XWpS/62.png',
      'https://i.postimg.cc/1XvgvShk/63.png',
      'https://i.postimg.cc/1zDfLw1c/64.png',
      'https://i.postimg.cc/pTxpxr2N/65.png',
      'https://i.postimg.cc/8czcJYJt/66.png',
      'https://i.postimg.cc/J0YnbQjm/67.png',
      'https://i.postimg.cc/J7pGVRvg/68.png',
      'https://i.postimg.cc/9Fzzcvjf/69.png',
      'https://i.postimg.cc/m2Mf3wYw/7.png',
      'https://i.postimg.cc/zXMvv0JF/70.png',
      'https://i.postimg.cc/g2ZJZ8jF/71.png',
      'https://i.postimg.cc/25N5FyLq/72.png',
      'https://i.postimg.cc/cCzxKLNL/73.png',
      'https://i.postimg.cc/05X2XcJ1/74.png',
      'https://i.postimg.cc/VLSsxnjr/75.png',
      'https://i.postimg.cc/ZK1Y4ncf/76.png',
      'https://i.postimg.cc/Qd18tDYj/77.png',
      'https://i.postimg.cc/tgbXnc8W/78.png',
      'https://i.postimg.cc/8CbTRHV3/79.png',
      'https://i.postimg.cc/mgsxmHVG/8.png',
      'https://i.postimg.cc/B6Q4MKSv/80.png',
      'https://i.postimg.cc/mDXRqgky/81.png',
      'https://i.postimg.cc/br4PyVQG/82.png',
      'https://i.postimg.cc/T2sfJ1ZR/83.png',
      'https://i.postimg.cc/QxWs4s3c/84.png',
      'https://i.postimg.cc/T3MxBSdF/85.png',
      'https://i.postimg.cc/pLfvvZyT/86.png',
      'https://i.postimg.cc/BvJ0nK1C/87.png',
      'https://i.postimg.cc/5tpMY2BW/88.png',
      'https://i.postimg.cc/bJJfQfgD/89.png',
      'https://i.postimg.cc/MpbCNprf/9.png',
      'https://i.postimg.cc/26KRG99H/90.png',
      'https://i.postimg.cc/kDrr36mK/91.png',
      'https://i.postimg.cc/MZnvSCwp/92.png',
      'https://i.postimg.cc/59DjNs9q/93.png',
      'https://i.postimg.cc/hPxvJVfF/94.png',
      'https://i.postimg.cc/qvTR2g3N/95.png',
      'https://i.postimg.cc/6Q6p1Szw/96.png',
      'https://i.postimg.cc/zGFf75C0/97.png',
      'https://i.postimg.cc/xds1rRFm/98.png',
      'https://i.postimg.cc/j5LdR7GF/99.png'
    ]
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Clean aesthetics, neutral tones, minimalist arrangements',
    theme: 'minimal',
    coverImage: 'https://i.postimg.cc/NfrbPGj8/1.png',
    images: [
      'https://i.postimg.cc/NfrbPGj8/1.png',
      'https://i.postimg.cc/ryRY7Nht/10.png',
      'https://i.postimg.cc/Cdy26Ryt/100.png',
      'https://i.postimg.cc/RC3V825Q/101.png',
      'https://i.postimg.cc/9XvFj1c3/102.png',
      'https://i.postimg.cc/MKVZZRGn/103.png',
      'https://i.postimg.cc/Jz8rsnyP/104.png',
      'https://i.postimg.cc/t4zXWjWy/105.png',
      'https://i.postimg.cc/mr2TS5y9/106.png',
      'https://i.postimg.cc/zft82Fxc/107.png',
      'https://i.postimg.cc/PxChgvcr/108.png',
      'https://i.postimg.cc/RF294V51/109.png',
      'https://i.postimg.cc/ydkr1mst/11.png',
      'https://i.postimg.cc/zvWNBZ8s/110.png',
      'https://i.postimg.cc/h47cMxT2/111.png',
      'https://i.postimg.cc/zXZ5QBk8/112.png',
      'https://i.postimg.cc/nLztmQnY/113.png',
      'https://i.postimg.cc/SN6qbhZ8/114.png',
      'https://i.postimg.cc/htKnS5wY/115.png',
      'https://i.postimg.cc/JzKLtQCz/116.png',
      'https://i.postimg.cc/yNbCyYdq/117.png',
      'https://i.postimg.cc/mD1fXfzP/118.png',
      'https://i.postimg.cc/D0VVRjLB/119.png',
      'https://i.postimg.cc/7hzs7qCN/12.png',
      'https://i.postimg.cc/L5zdStVR/120.png',
      'https://i.postimg.cc/Dfs31h3D/121.png',
      'https://i.postimg.cc/65XJ0P9Q/122.png',
      'https://i.postimg.cc/dtjMS91j/123.png',
      'https://i.postimg.cc/DwfVVb4k/124.png',
      'https://i.postimg.cc/FHTMhs0f/125.png',
      'https://i.postimg.cc/s28bZ66s/126.png',
      'https://i.postimg.cc/cJ6VCycF/127.png',
      'https://i.postimg.cc/Pxw9bW9Z/128.png',
      'https://i.postimg.cc/L5F7xqFW/129.png',
      'https://i.postimg.cc/L6d0Sg7Q/13.png',
      'https://i.postimg.cc/Bb5zkqqn/130.png',
      'https://i.postimg.cc/mZ7KtSQW/131.png',
      'https://i.postimg.cc/WbjCrJnF/132.png',
      'https://i.postimg.cc/c4mjc49D/133.png',
      'https://i.postimg.cc/6ppPbJFB/134.png',
      'https://i.postimg.cc/Bn7Vd7GH/135.png',
      'https://i.postimg.cc/25qKmdzJ/136.png',
      'https://i.postimg.cc/s2t02Bx2/137.png',
      'https://i.postimg.cc/1tw7V9Vr/138.png',
      'https://i.postimg.cc/T1x7rZrM/139.png',
      'https://i.postimg.cc/ZKrs5Kzb/14.png',
      'https://i.postimg.cc/1XKWMJHg/140.png',
      'https://i.postimg.cc/sgxn9PZX/141.png',
      'https://i.postimg.cc/Vs9HYk8Y/142.png',
      'https://i.postimg.cc/28z93Nkn/143.png',
      'https://i.postimg.cc/bN3CtVrW/144.png',
      'https://i.postimg.cc/g27gMwvK/145.png',
      'https://i.postimg.cc/jjJZBscY/146.png',
      'https://i.postimg.cc/nzb0J6Sj/147.png',
      'https://i.postimg.cc/qRsQMjWm/148.png',
      'https://i.postimg.cc/J0RxyjLR/149.png',
      'https://i.postimg.cc/YCRXQnST/15.png',
      'https://i.postimg.cc/Hn32bjYX/150.png',
      'https://i.postimg.cc/NGxb3C6F/151.png',
      'https://i.postimg.cc/Hss3d0z2/152.png',
      'https://i.postimg.cc/MKP5Tcr8/153.png',
      'https://i.postimg.cc/4xY5hJrH/154.png',
      'https://i.postimg.cc/wjnkXCpf/155.png',
      'https://i.postimg.cc/R0fLXgCM/156.png',
      'https://i.postimg.cc/MTSb41X1/157.png',
      'https://i.postimg.cc/85mBVsr9/158.png',
      'https://i.postimg.cc/j2q6qKH5/159.png',
      'https://i.postimg.cc/fRD2tnMx/16.png',
      'https://i.postimg.cc/44wbL7Gh/160.png',
      'https://i.postimg.cc/C5vGzt74/161.png',
      'https://i.postimg.cc/653VDW6b/162.png',
      'https://i.postimg.cc/wTG5zC7q/163.png',
      'https://i.postimg.cc/Mpf7p9Qy/164.png',
      'https://i.postimg.cc/bvXQD1x4/165.png',
      'https://i.postimg.cc/fbxYxk5y/166.png',
      'https://i.postimg.cc/C1SkJY6N/167.png',
      'https://i.postimg.cc/rmjWPbBL/168.png',
      'https://i.postimg.cc/j2kfsfqg/169.png',
      'https://i.postimg.cc/yNNLjmgx/17.png',
      'https://i.postimg.cc/D0zsk6h4/170.png',
      'https://i.postimg.cc/ryhxGBG1/171.png',
      'https://i.postimg.cc/28Vv00TP/172.png',
      'https://i.postimg.cc/7ZzzkbF9/173.png',
      'https://i.postimg.cc/DyHGH1Mm/174.png',
      'https://i.postimg.cc/HLCysdHg/175.png',
      'https://i.postimg.cc/GpJs4Vhs/176.png',
      'https://i.postimg.cc/V6f0ngdZ/177.png',
      'https://i.postimg.cc/rmf0J44V/178.png',
      'https://i.postimg.cc/SRjXtKLW/179.png',
      'https://i.postimg.cc/nLw0PXBk/18.png',
      'https://i.postimg.cc/hvwJFqMN/180.png',
      'https://i.postimg.cc/h43QQ9gM/181.png',
      'https://i.postimg.cc/wTyyX7jz/182.png',
      'https://i.postimg.cc/gkCwNmxZ/183.png',
      'https://i.postimg.cc/Gmv4fVDS/184.png',
      'https://i.postimg.cc/pdxmMCYV/185.png',
      'https://i.postimg.cc/435mfcB6/186.png',
      'https://i.postimg.cc/W31th4HQ/187.png',
      'https://i.postimg.cc/tTvJPj07/188.png',
      'https://i.postimg.cc/gjwJHTds/189.png',
      'https://i.postimg.cc/ydgv47Tz/19.png',
      'https://i.postimg.cc/XqTvHkYb/190.png',
      'https://i.postimg.cc/9XSzQCtn/191.png',
      'https://i.postimg.cc/jS6jcNVp/192.png',
      'https://i.postimg.cc/7hTH2JMQ/193.png',
      'https://i.postimg.cc/NMnGFkTH/194.png',
      'https://i.postimg.cc/v81fzP0C/195.png',
      'https://i.postimg.cc/X7dFMrS8/196.png',
      'https://i.postimg.cc/y8TZd2N3/197.png',
      'https://i.postimg.cc/yNQ3h9cV/198.png',
      'https://i.postimg.cc/7LYTTXCs/199.png',
      'https://i.postimg.cc/MGzDTybt/2.png',
      'https://i.postimg.cc/RFkGv2PJ/20.png',
      'https://i.postimg.cc/LXJYxX3j/200.png',
      'https://i.postimg.cc/qRWtST1S/201.png',
      'https://i.postimg.cc/2yvqfKJ6/202.png',
      'https://i.postimg.cc/y6S39DdH/203.png',
      'https://i.postimg.cc/YqKGxtGm/204.png',
      'https://i.postimg.cc/QxQB4v1Y/205.png',
      'https://i.postimg.cc/BnJjdNCS/206.png',
      'https://i.postimg.cc/T3QKGmkr/207.png',
      'https://i.postimg.cc/ZqRCqRgX/208.png',
      'https://i.postimg.cc/q75g6rHq/209.png',
      'https://i.postimg.cc/4ypPywML/21.png',
      'https://i.postimg.cc/50Qywrf3/210.png',
      'https://i.postimg.cc/qBKj1MRs/22.png',
      'https://i.postimg.cc/PrkK9spB/23.png',
      'https://i.postimg.cc/7YMXysSb/24.png',
      'https://i.postimg.cc/Dwv6frc6/25.png',
      'https://i.postimg.cc/T3t9KK76/26.png',
      'https://i.postimg.cc/fbkvmMp0/27.png',
      'https://i.postimg.cc/bvM9RKfV/28.png',
      'https://i.postimg.cc/8cgd2M5h/29.png',
      'https://i.postimg.cc/3x59MMks/3.png',
      'https://i.postimg.cc/1tqc7J9m/30.png',
      'https://i.postimg.cc/MH00qHMg/31.png',
      'https://i.postimg.cc/G3vxk77z/32.png',
      'https://i.postimg.cc/yYBXnm2K/33.png',
      'https://i.postimg.cc/X78KPZ0C/34.png',
      'https://i.postimg.cc/fRR7Qwwg/35.png',
      'https://i.postimg.cc/g2tVYfjc/36.png',
      'https://i.postimg.cc/xdkKqtNv/37.png',
      'https://i.postimg.cc/q792Ky29/38.png',
      'https://i.postimg.cc/8cbvxYxS/39.png',
      'https://i.postimg.cc/52BgbPv6/4.png',
      'https://i.postimg.cc/nrx7RxR2/40.png',
      'https://i.postimg.cc/SsCCfRrj/41.png',
      'https://i.postimg.cc/dQRG773x/42.png',
      'https://i.postimg.cc/KvZBtZgv/43.png',
      'https://i.postimg.cc/3xNGbnBs/44.png',
      'https://i.postimg.cc/L6NfTrzk/45.png',
      'https://i.postimg.cc/0y4SgDXb/46.png',
      'https://i.postimg.cc/pdnFPr3k/47.png',
      'https://i.postimg.cc/pTbnrxHv/48.png',
      'https://i.postimg.cc/pTf5n7WF/49.png',
      'https://i.postimg.cc/s1FPRSgY/5.png',
      'https://i.postimg.cc/XqnGK8qD/50.png',
      'https://i.postimg.cc/sxKBThZf/51.png',
      'https://i.postimg.cc/TYY5pCZK/52.png',
      'https://i.postimg.cc/441hfrFC/53.png',
      'https://i.postimg.cc/02WMm7sc/54.png',
      'https://i.postimg.cc/CxRZ4dMY/55.png',
      'https://i.postimg.cc/JzSsYmtX/56.png',
      'https://i.postimg.cc/Lsfnr7Zb/57.png',
      'https://i.postimg.cc/d1YLvB2t/58.png',
      'https://i.postimg.cc/hj1hGds8/59.png',
      'https://i.postimg.cc/xC4ytBrF/6.png',
      'https://i.postimg.cc/x8j8N1pw/60.png',
      'https://i.postimg.cc/ZnfR8z1C/61.png',
      'https://i.postimg.cc/CL1dFdqD/62.png',
      'https://i.postimg.cc/NGb5qR5B/63.png',
      'https://i.postimg.cc/Gh5t9rFf/64.png',
      'https://i.postimg.cc/FHkRLqGH/65.png',
      'https://i.postimg.cc/tg0gt5mt/66.png',
      'https://i.postimg.cc/CKjxvq3y/67.png',
      'https://i.postimg.cc/85NPxCG7/68.png',
      'https://i.postimg.cc/50gNJM9n/69.png',
      'https://i.postimg.cc/TwFNpKPw/7.png',
      'https://i.postimg.cc/BbvZQwXs/70.png',
      'https://i.postimg.cc/66H51wmQ/71.png',
      'https://i.postimg.cc/WzfND6kZ/72.png',
      'https://i.postimg.cc/HsVWqKq9/73.png',
      'https://i.postimg.cc/yYt6sjB4/74.png',
      'https://i.postimg.cc/s2RVZ2vT/75.png',
      'https://i.postimg.cc/3wC3jHGY/76.png',
      'https://i.postimg.cc/63WtY1VR/77.png',
      'https://i.postimg.cc/nz3Z5YTW/78.png',
      'https://i.postimg.cc/HnjHCchk/79.png',
      'https://i.postimg.cc/ZnvPgj4Y/8.png',
      'https://i.postimg.cc/3rbYF1k4/80.png',
      'https://i.postimg.cc/8c3Gkp2B/81.png',
      'https://i.postimg.cc/pXhxGjj0/82.png',
      'https://i.postimg.cc/WbBVQ46s/83.png',
      'https://i.postimg.cc/QdcDsr01/84.png',
      'https://i.postimg.cc/JhmLzd2g/85.png',
      'https://i.postimg.cc/fbKhtf4b/86.png',
      'https://i.postimg.cc/NMjv12Yk/87.png',
      'https://i.postimg.cc/vB2FX8ZF/88.png',
      'https://i.postimg.cc/MHckLknc/89.png',
      'https://i.postimg.cc/k5MpZrZn/9.png',
      'https://i.postimg.cc/j2GV08fM/90.png',
      'https://i.postimg.cc/Pfcnwq71/91.png',
      'https://i.postimg.cc/CLqTHgyX/92.png',
      'https://i.postimg.cc/fRcGpfRv/93.png',
      'https://i.postimg.cc/kgPrTpq4/94.png',
      'https://i.postimg.cc/KYQdvcLk/95.png',
      'https://i.postimg.cc/wB9CpRtY/96.png',
      'https://i.postimg.cc/Pxx0LGz6/97.png',
      'https://i.postimg.cc/pT64z0sP/98.png',
      'https://i.postimg.cc/D04DgqNL/99.png'
    ]
  },
  {
    id: 'business-professional',
    name: 'Business Professional',
    description: 'Corporate elegance, office aesthetics, professional tools',
    theme: 'business',
    coverImage: 'https://i.postimg.cc/VNCRLn6H/1.png',
    images: [
      'https://i.postimg.cc/VNCRLn6H/1.png',
      'https://i.postimg.cc/WbY6GXqH/10.png',
      'https://i.postimg.cc/2SVpGccb/100.png',
      'https://i.postimg.cc/FHqMBy8P/101.png',
      'https://i.postimg.cc/rprBXdLq/102.png',
      'https://i.postimg.cc/ydCwVVVc/103.png',
      'https://i.postimg.cc/4dvjyrdM/104.png',
      'https://i.postimg.cc/kGnzbfR5/105.png',
      'https://i.postimg.cc/vT3jLf5t/106.png',
      'https://i.postimg.cc/8kHqSQxf/107.png',
      'https://i.postimg.cc/5NKTX54x/108.png',
      'https://i.postimg.cc/VkSTnSvX/109.png',
      'https://i.postimg.cc/g2wyN8vk/11.png',
      'https://i.postimg.cc/DwtNg24H/110.png',
      'https://i.postimg.cc/LsLbQrzX/111.png',
      'https://i.postimg.cc/Jn8dfPqQ/112.png',
      'https://i.postimg.cc/4d1FsV2R/113.png',
      'https://i.postimg.cc/j2d352Bw/114.png',
      'https://i.postimg.cc/j2ggJKr8/115.png',
      'https://i.postimg.cc/05cH4GJp/116.png',
      'https://i.postimg.cc/sDx0CBpb/117.png',
      'https://i.postimg.cc/m2npLbjk/118.png',
      'https://i.postimg.cc/y8SQWwpP/119.png',
      'https://i.postimg.cc/vZprjTz7/12.png',
      'https://i.postimg.cc/fbnHdB6h/120.png',
      'https://i.postimg.cc/5tBsS8VQ/121.png',
      'https://i.postimg.cc/85wwqDs1/122.png',
      'https://i.postimg.cc/rsmgTbt5/123.png',
      'https://i.postimg.cc/4ySPx5zq/124.png',
      'https://i.postimg.cc/3rSn1KP1/125.png',
      'https://i.postimg.cc/jjPHrTgp/13.png',
      'https://i.postimg.cc/ydKF1G2k/14.png',
      'https://i.postimg.cc/wvkD7VdF/15.png',
      'https://i.postimg.cc/PJrYZwXH/16.png',
      'https://i.postimg.cc/6qjRhpqv/17.png',
      'https://i.postimg.cc/VsDjwDgk/18.png',
      'https://i.postimg.cc/CL5bxkrH/19.png',
      'https://i.postimg.cc/T3S06CRD/2.png',
      'https://i.postimg.cc/024DMjLg/20.png',
      'https://i.postimg.cc/cL8YQZSv/21.png',
      'https://i.postimg.cc/1zhFBTmJ/22.png',
      'https://i.postimg.cc/TPVD49hG/23.png',
      'https://i.postimg.cc/W3skLkJZ/24.png',
      'https://i.postimg.cc/WzHFkYYm/25.png',
      'https://i.postimg.cc/Hx37pkQh/26.png',
      'https://i.postimg.cc/Bb6PtfpQ/27.png',
      'https://i.postimg.cc/SQTz3jQX/28.png',
      'https://i.postimg.cc/281BDm30/29.png',
      'https://i.postimg.cc/QtZqBCKN/3.png',
      'https://i.postimg.cc/65F46Svt/30.png',
      'https://i.postimg.cc/MpRMnD7R/31.png',
      'https://i.postimg.cc/xd2kMz5Z/32.png',
      'https://i.postimg.cc/jj4DXSkS/33.png',
      'https://i.postimg.cc/d1QLSczm/34.png',
      'https://i.postimg.cc/k4jD0hCr/35.png',
      'https://i.postimg.cc/sxv1s9fM/36.png',
      'https://i.postimg.cc/6qgq32TY/37.png',
      'https://i.postimg.cc/BZVXNyNH/38.png',
      'https://i.postimg.cc/5NQjr3kG/39.png',
      'https://i.postimg.cc/BntpkdG3/4.png',
      'https://i.postimg.cc/MpyH6Gwm/40.png',
      'https://i.postimg.cc/MpkXJQCG/41.png',
      'https://i.postimg.cc/QMhtHrxG/42.png',
      'https://i.postimg.cc/VNgNtHdS/43.png',
      'https://i.postimg.cc/RF0ZLQHg/44.png',
      'https://i.postimg.cc/mD62Xz3B/45.png',
      'https://i.postimg.cc/3N4rP89p/46.png',
      'https://i.postimg.cc/FzMFvMn6/47.png',
      'https://i.postimg.cc/1R23DF5K/48.png',
      'https://i.postimg.cc/c434hJvG/49.png',
      'https://i.postimg.cc/9MPYy2yd/5.png',
      'https://i.postimg.cc/Gm1351D8/50.png',
      'https://i.postimg.cc/52q9ck5P/51.png',
      'https://i.postimg.cc/k5JJ7Ff7/52.png',
      'https://i.postimg.cc/43WJy7SV/53.png',
      'https://i.postimg.cc/TwhTDdzS/54.png',
      'https://i.postimg.cc/QtPhkLsM/55.png',
      'https://i.postimg.cc/wMmHwWTQ/56.png',
      'https://i.postimg.cc/z3YN6nyZ/57.png',
      'https://i.postimg.cc/ZYBdk4WV/58.png',
      'https://i.postimg.cc/Pfg8T9Zh/59.png',
      'https://i.postimg.cc/cCsMmzcV/6.png',
      'https://i.postimg.cc/RVwJFdQt/60.png',
      'https://i.postimg.cc/3xByjwqJ/61.png',
      'https://i.postimg.cc/jjSDMbV6/62.png',
      'https://i.postimg.cc/Bv7XyVsr/63.png',
      'https://i.postimg.cc/hjJfq1tf/64.png',
      'https://i.postimg.cc/nz6MV9XT/65.png',
      'https://i.postimg.cc/sx7xMfSz/66.png',
      'https://i.postimg.cc/59C67grr/67.png',
      'https://i.postimg.cc/qMHg9nVv/68.png',
      'https://i.postimg.cc/3xKNwTwM/69.png',
      'https://i.postimg.cc/L5Nk0VCh/7.png',
      'https://i.postimg.cc/J43tmnMc/70.png',
      'https://i.postimg.cc/FHDRdBfY/71.png',
      'https://i.postimg.cc/wBMBhQJ0/72.png',
      'https://i.postimg.cc/V6bLhsKt/73.png',
      'https://i.postimg.cc/Pq75KvQh/74.png',
      'https://i.postimg.cc/zvZXYmQc/75.png',
      'https://i.postimg.cc/SR6QyTFN/76.png',
      'https://i.postimg.cc/tRW4tTZQ/77.png',
      'https://i.postimg.cc/vHyHPsf1/78.png',
      'https://i.postimg.cc/J4Q7v25p/79.png',
      'https://i.postimg.cc/L4TVXH9R/8.png',
      'https://i.postimg.cc/fRTWNfHD/80.png',
      'https://i.postimg.cc/W1WNbqKr/81.png',
      'https://i.postimg.cc/MGnWcK2L/82.png',
      'https://i.postimg.cc/rp7q5Xqw/83.png',
      'https://i.postimg.cc/pT8RZGdY/84.png',
      'https://i.postimg.cc/L5pR0tYd/85.png',
      'https://i.postimg.cc/vTtMR4f4/86.png',
      'https://i.postimg.cc/SQ6mYv3m/87.png',
      'https://i.postimg.cc/15ysGK1w/88.png',
      'https://i.postimg.cc/MKtxdjz4/89.png',
      'https://i.postimg.cc/Hsk98fnM/9.png',
      'https://i.postimg.cc/mgD4q2Dr/90.png',
      'https://i.postimg.cc/9Qn2j5RY/91.png',
      'https://i.postimg.cc/fbSNz2Yn/92.png',
      'https://i.postimg.cc/d1MKL297/93.png',
      'https://i.postimg.cc/vBWw94P0/94.png',
      'https://i.postimg.cc/2yrRxCMr/95.png',
      'https://i.postimg.cc/ZnHk71z3/96.png',
      'https://i.postimg.cc/qBxdvC6R/97.png',
      'https://i.postimg.cc/28jNb8nx/98.png',
      'https://i.postimg.cc/ncdbvbkf/99.png'
    ]
  },
  {
    id: 'modern-tech',
    name: 'Modern Tech',
    description: 'Digital devices, modern workspace, tech aesthetics',
    theme: 'tech',
    coverImage: 'https://i.postimg.cc/90g2Xvg2/1.png',
    images: [
      'https://i.postimg.cc/90g2Xvg2/1.png',
      'https://i.postimg.cc/8cc8YZp0/10.png',
      'https://i.postimg.cc/y8ZD5Pn8/100.png'
    ]
  },
  {
    id: 'wellness-lifestyle',
    name: 'Wellness Lifestyle',
    description: 'Self-care, wellness products, healthy living',
    theme: 'wellness',
    coverImage: 'https://i.postimg.cc/MTjrNHg1/127161.png',
    images: [
      'https://i.postimg.cc/MTjrNHg1/127161.png',
      'https://i.postimg.cc/6p9gq9GN/17231.png',
      'https://i.postimg.cc/PJWVfcXx/182317.png'
    ]
  },
  {
    id: 'travel-adventure',
    name: 'Travel Adventure',
    description: 'Maps, passports, travel essentials, wanderlust',
    theme: 'travel',
    coverImage: 'https://i.postimg.cc/02VLGyr8/1.png',
    images: [
      'https://i.postimg.cc/02VLGyr8/1.png',
      'https://i.postimg.cc/xjR7Y1vK/10.png',
      'https://i.postimg.cc/TwC83VLX/100.png'
    ]
  },
  {
    id: 'food-lifestyle',
    name: 'Food Lifestyle',
    description: 'Coffee culture, culinary aesthetics, food styling',
    theme: 'food',
    coverImage: 'https://i.postimg.cc/6qBxt1FS/file-1.png',
    images: [
      'https://i.postimg.cc/6qBxt1FS/file-1.png',
      'https://i.postimg.cc/43hg5cz8/file-11.png',
      'https://i.postimg.cc/DZkKYz67/file-12.png'
    ]
  },
  {
    id: 'fashion-beauty',
    name: 'Fashion Beauty',
    description: 'Beauty products, fashion accessories, style elements',
    theme: 'fashion',
    coverImage: 'https://i.postimg.cc/gjXRNPZt/1.png',
    images: [
      'https://i.postimg.cc/gjXRNPZt/1.png',
      'https://i.postimg.cc/bvyt4nnt/10.png',
      'https://i.postimg.cc/2SFWHG1Y/11.png'
    ]
  }
];

// Helper functions for moodboard functionality
export const getMoodboardCollection = (id: string): MoodboardCollection | undefined => {
  return MoodboardCollections.find(collection => collection.id === id);
};

export const getMoodboardsByTheme = (theme: string): MoodboardCollection[] => {
  return MoodboardCollections.filter(collection => collection.theme === theme);
};

export const getAllMoodboardThemes = (): string[] => {
  return [...new Set(MoodboardCollections.map(collection => collection.theme))];
};