version: '1.0'

# Backup configuration
backup:
  schedule:
    - name: daily
      frequency: "0 2 * * *"  # Every day at 2 AM
      retention: 7  # Keep 7 daily backups
    - name: weekly
      frequency: "0 3 * * 0"  # Every Sunday at 3 AM
      retention: 4  # Keep 4 weekly backups
    - name: monthly
      frequency: "0 4 1 * *"  # First day of month at 4 AM
      retention: 3  # Keep 3 monthly backups

  targets:
    - name: website-files
      source: /var/www/sselfie.studio
      type: filesystem
      
    - name: database
      source: sselfie_production
      type: postgresql
      
    - name: user-uploads
      source: /var/www/sselfie.studio/uploads
      type: filesystem

  storage:
    provider: aws-s3
    bucket: sselfie-backups
    region: us-east-1
    path: production/
    encryption: AES-256

  notifications:
    on_success:
      - type: email
        recipient: admin@sselfie.studio
    on_failure:
      - type: email
        recipient: admin@sselfie.studio
      - type: slack
        webhook: ${SLACK_WEBHOOK_URL}

  compression:
    algorithm: zstd
    level: 3

  monitoring:
    enabled: true
    metrics_retention: 30  # days
    alert_on_failure: true