repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-ll"]
        files: .py$

-   repo: local
    hooks:
    -   id: test-coverage
        name: Check test coverage
        entry: python -m pytest --cov=. --cov-fail-under=80
        language: system
        pass_filenames: false
        always_run: true
    
    -   id: documentation-check
        name: Check documentation requirements
        entry: python scripts/check_documentation.py
        language: system
        pass_filenames: false
        always_run: true