import React from 'react';

interface WorkingComponentProps {
  className?: string;
}

export const WorkingComponent: React.FC<WorkingComponentProps> = ({ 
  className = '' 
}) => {
  return (
    <div className={`luxury-component ${className}`}>
      <h2 className="text-2xl font-bold text-black">
        WorkingComponent
      </h2>
      <p className="text-gray-600 mt-2">
        Generated by Aria
      </p>
    </div>
  );
};

export default WorkingComponent;
