import React from 'react';

interface StreamingAgentChatProps {
  className?: string;
}

export const StreamingAgentChat: React.FC<StreamingAgentChatProps> = ({ 
  className = '' 
}) => {
  return (
    <div className={`luxury-component ${className}`}>
      <h2 className="text-2xl font-bold text-black">
        StreamingAgentChat
      </h2>
      <p className="text-gray-600 mt-2">
        Generated by Quinn
      </p>
    </div>
  );
};

export default StreamingAgentChat;
