/**
 * Notification System Type Definitions
 * 
 * This file defines all types for the notification system following the type-safe 
 * infrastructure patterns established in the SSELFIE Brand Studio application.
 * 
 * @fileoverview Type definitions for notifications, preferences, email templates, and hook interfaces
 * @version 1.0.0
 */

/**
 * Unique identifier for a notification
 */
export type NotificationId = string;

/**
 * Unique identifier for a user
 */
export type UserId = string;

/**
 * Available notification types in the system
 * Each type corresponds to a specific event or action that generates notifications
 */
export type NotificationType = 
  | 'model_training_complete'    // AI model training finished
  | 'payment_confirmation'       // Payment processed successfully
  | 'onboarding_status'         // Onboarding step completed or updated
  | 'generation_limit_warning'  // User approaching generation limits
  | 'system_update'             // System maintenance or updates
  | 'agent_insight'             // AI agent generated insights
  | 'task_completed'            // Background task finished
  | 'error_alert';              // System errors requiring attention

/**
 * Priority levels for notifications
 * Affects display order, email sending preferences, and user attention
 */
export type NotificationPriority = 'high' | 'medium' | 'low';

/**
 * Current status of a notification
 */
export type NotificationStatus = 'unread' | 'read' | 'dismissed';

/**
 * Base notification interface containing common fields
 * All specific notification types extend this interface
 */
export interface BaseNotification {
  /** Unique notification identifier */
  id: NotificationId;
  /** ID of the user who should receive this notification */
  userId: UserId;
  /** Type of notification determining its behavior and display */
  type: NotificationType;
  /** Short, descriptive title for the notification */
  title: string;
  /** Detailed message content */
  message: string;
  /** Priority level affecting display and processing */
  priority: NotificationPriority;
  /** Current status of the notification */
  status: NotificationStatus;
  /** When the notification was created */
  createdAt: Date;
  /** When the notification was last updated */
  updatedAt: Date;
  /** When the notification was marked as read (if applicable) */
  readAt?: Date;
  /** When the notification was dismissed (if applicable) */
  dismissedAt?: Date;
}

/**
 * Notification for completed model training
 * Contains training-specific metadata and results
 */
export interface ModelTrainingNotification extends BaseNotification {
  type: 'model_training_complete';
  data: {
    /** Unique identifier of the trained model */
    modelId: string;
    /** Human-readable name of the model */
    modelName: string;
    /** Training duration in minutes */
    trainingDuration: number;
    /** Model accuracy percentage (if available) */
    accuracy?: number;
  };
}

/**
 * Notification for payment confirmations
 * Contains transaction details and billing information
 */
export interface PaymentNotification extends BaseNotification {
  type: 'payment_confirmation';
  data: {
    /** Unique transaction/payment identifier */
    transactionId: string;
    /** Payment amount */
    amount: number;
    /** Payment currency (e.g., 'USD', 'EUR') */
    currency: string;
    /** Name of the purchased plan */
    planType: string;
    /** Next billing date (for recurring payments) */
    nextBillingDate?: string;
  };
}

/**
 * Notification for onboarding progress updates
 * Tracks user progress through setup process
 */
export interface OnboardingNotification extends BaseNotification {
  type: 'onboarding_status';
  data: {
    /** Name/identifier of the onboarding step */
    step: string;
    /** Whether the step was completed */
    completed: boolean;
    /** Description of what the user should do next */
    nextAction?: string;
  };
}

/**
 * Notification for AI agent insights
 * Contains insights generated by AI agents in the system
 */
export interface AgentInsightNotification extends BaseNotification {
  type: 'agent_insight';
  data: {
    /** Name of the AI agent that generated the insight */
    agentName: string;
    /** Category of insight */
    insightType: 'strategic' | 'technical' | 'operational' | 'urgent';
    /** Additional context data for the insight */
    context?: Record<string, any>;
  };
}

/**
 * Union type of all possible notification types
 * Use this for functions that accept any notification
 */
export type Notification = 
  | ModelTrainingNotification 
  | PaymentNotification 
  | OnboardingNotification 
  | AgentInsightNotification 
  | BaseNotification;

/**
 * User preferences for notification delivery and filtering
 * Controls how and when notifications are sent to users
 */
export interface NotificationPreferences {
  /** Enable/disable email notifications */
  emailEnabled: boolean;
  /** Enable/disable Slack notifications */
  slackEnabled: boolean;
  /** Enable/disable push notifications */
  pushEnabled: boolean;
  /** How frequently to send notification emails */
  frequency: 'immediate' | 'hourly' | 'daily';
  /** Quiet hours configuration */
  quietHours?: {
    /** Whether quiet hours are enabled */
    enabled: boolean;
    /** Start time in HH:MM format (24-hour) */
    start: string;
    /** End time in HH:MM format (24-hour) */
    end: string;
  };
  /** Which notification types to receive */
  types: Record<NotificationType, boolean>;
  /** Which priority levels to receive */
  priorities: Record<NotificationPriority, boolean>;
}

/**
 * API response format for notification queries
 * Includes pagination and count information
 */
export interface NotificationResponse {
  /** Array of notification objects */
  notifications: Notification[];
  /** Total number of notifications (for pagination) */
  totalCount: number;
  /** Number of unread notifications */
  unreadCount: number;
  /** Whether there are more notifications available */
  hasMore: boolean;
}

/**
 * Configuration options for the notification service
 * Used to customize behavior and enable/disable features
 */
export interface NotificationServiceConfig {
  /** Feature flag to check before enabling notifications */
  enableFeatureFlag?: string;
  /** Whether to enable email service integration */
  emailService?: boolean;
  /** Whether to enable real-time updates via WebSocket */
  realTimeUpdates?: boolean;
  /** Whether to persist notifications to database */
  persistToDatabase?: boolean;
}

/**
 * Email template definition for notifications
 * Used by the email service to generate HTML emails
 */
export interface NotificationEmailTemplate {
  /** Notification type this template applies to */
  type: NotificationType;
  /** Email subject line template */
  subject: string;
  /** HTML template content */
  template: string;
  /** Variables to interpolate in the template */
  variables: Record<string, any>;
}

/**
 * Email queue item for background processing
 * Represents a notification waiting to be sent via email
 */
export interface EmailQueueItem {
  /** Unique queue item identifier */
  id: string;
  /** Target user ID */
  userId: UserId;
  /** Notification to be sent */
  notification: Notification;
  /** Email template to use */
  template: NotificationEmailTemplate;
  /** Number of send attempts made */
  attempts: number;
  /** Maximum number of attempts before giving up */
  maxAttempts: number;
  /** When the email was scheduled to be sent */
  scheduledAt: Date;
  /** When the last attempt was made (if any) */
  lastAttemptAt?: Date;
  /** Current status of the email */
  status: 'pending' | 'sent' | 'failed' | 'cancelled';
  /** Error message if sending failed */
  error?: string;
}

/**
 * State interface for the useNotifications hook
 * Represents the current state of the notification system
 */
export interface UseNotificationsState {
  /** Array of current notifications */
  notifications: Notification[];
  /** Number of unread notifications */
  unreadCount: number;
  /** Whether data is currently being loaded */
  loading: boolean;
  /** Current error message (if any) */
  error: string | null;
  /** Whether there are more notifications to load */
  hasMore: boolean;
}

/**
 * Actions interface for the useNotifications hook
 * Defines all available notification management functions
 */
export interface UseNotificationsActions {
  /** Mark a specific notification as read */
  markAsRead: (id: NotificationId) => Promise<void>;
  /** Mark all notifications as read */
  markAllAsRead: () => Promise<void>;
  /** Dismiss/hide a specific notification */
  dismiss: (id: NotificationId) => Promise<void>;
  /** Refresh the notification list */
  refresh: () => Promise<void>;
  /** Load more notifications (for pagination) */
  loadMore: () => Promise<void>;
}

/**
 * Complete return type for the useNotifications hook
 * Combines state and actions for comprehensive notification management
 */
export interface UseNotificationsReturn extends UseNotificationsState, UseNotificationsActions {}