// WORKING flatlay collections with DIRECT paths to actual files
// Generated by emergency fix script - ALIGNED WITH ACTUAL FILE STRUCTURE

export interface FlatlayImage {
  id: string;
  url: string;
  title: string;
  category: string;
  description: string;
}

export interface FlatlayCollection {
  id: string;
  name: string;
  description: string;
  aesthetic: string;
  backgroundImage: string;
  images: FlatlayImage[];
  colors: string[];
  fonts: string[];
}

// WORKING flatlay collections with verified file paths
export const cleanedFlatlayCollections: FlatlayCollection[] = [
  {
    "id": "luxury-minimal",
    "name": "Luxury Minimal",
    "description": "Clean white backgrounds, designer accessories, minimal styling",
    "aesthetic": "Clean sophistication with generous white space",
    "backgroundImage": "/flatlays/luxury-minimal/luxury-minimal-001.png",
    "colors": [
      "#ffffff",
      "#f8f9fa",
      "#e9ecef",
      "#000000",
      "#6c757d"
    ],
    "fonts": [
      "Times New Roman",
      "Helvetica Neue",
      "Arial"
    ],
    "images": [
      {
        "id": "luxury-minimal-1",
        "url": "/flatlays/luxury-minimal/luxury-minimal-001.png",
        "title": "Luxury Minimal 001",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-2",
        "url": "/flatlays/luxury-minimal/luxury-minimal-002.png",
        "title": "Luxury Minimal 002",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-3",
        "url": "/flatlays/luxury-minimal/luxury-minimal-003.png",
        "title": "Luxury Minimal 003",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-4",
        "url": "/flatlays/luxury-minimal/luxury-minimal-004.png",
        "title": "Luxury Minimal 004",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-5",
        "url": "/flatlays/luxury-minimal/luxury-minimal-005.png",
        "title": "Luxury Minimal 005",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-6",
        "url": "/flatlays/luxury-minimal/luxury-minimal-006.png",
        "title": "Luxury Minimal 006",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-7",
        "url": "/flatlays/luxury-minimal/luxury-minimal-007.png",
        "title": "Luxury Minimal 007",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-8",
        "url": "/flatlays/luxury-minimal/luxury-minimal-008.png",
        "title": "Luxury Minimal 008",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-9",
        "url": "/flatlays/luxury-minimal/luxury-minimal-009.png",
        "title": "Luxury Minimal 009",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-10",
        "url": "/flatlays/luxury-minimal/luxury-minimal-010.png",
        "title": "Luxury Minimal 010",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-11",
        "url": "/flatlays/luxury-minimal/luxury-minimal-011.png",
        "title": "Luxury Minimal 011",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-12",
        "url": "/flatlays/luxury-minimal/luxury-minimal-012.png",
        "title": "Luxury Minimal 012",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-13",
        "url": "/flatlays/luxury-minimal/luxury-minimal-013.png",
        "title": "Luxury Minimal 013",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-14",
        "url": "/flatlays/luxury-minimal/luxury-minimal-014.png",
        "title": "Luxury Minimal 014",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-15",
        "url": "/flatlays/luxury-minimal/luxury-minimal-015.png",
        "title": "Luxury Minimal 015",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-16",
        "url": "/flatlays/luxury-minimal/luxury-minimal-016.png",
        "title": "Luxury Minimal 016",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-17",
        "url": "/flatlays/luxury-minimal/luxury-minimal-017.png",
        "title": "Luxury Minimal 017",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-18",
        "url": "/flatlays/luxury-minimal/luxury-minimal-018.png",
        "title": "Luxury Minimal 018",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      },
      {
        "id": "luxury-minimal-19",
        "url": "/flatlays/luxury-minimal/luxury-minimal-019.png",
        "title": "Luxury Minimal 019",
        "category": "Luxury Minimal",
        "description": "Luxury Minimal lifestyle flatlay"
      }
    ]
  },
  {
    "id": "editorial-magazine",
    "name": "Editorial Magazine",
    "description": "High-fashion editorial styling with dramatic lighting and artistic composition",
    "aesthetic": "Sophisticated editorial with dramatic contrast",
    "backgroundImage": "/flatlays/editorial-magazine/editorial-magazine-020.png",
    "colors": [
      "#000000",
      "#ffffff",
      "#f5f5f5",
      "#333333",
      "#666666"
    ],
    "fonts": [
      "Times New Roman",
      "Playfair Display",
      "Didot"
    ],
    "images": [
      {
        "id": "editorial-magazine-1",
        "url": "/flatlays/editorial-magazine/editorial-magazine-020.png",
        "title": "Editorial Magazine 020",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-2",
        "url": "/flatlays/editorial-magazine/editorial-magazine-021.png",
        "title": "Editorial Magazine 021",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-3",
        "url": "/flatlays/editorial-magazine/editorial-magazine-022.png",
        "title": "Editorial Magazine 022",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-4",
        "url": "/flatlays/editorial-magazine/editorial-magazine-023.png",
        "title": "Editorial Magazine 023",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-5",
        "url": "/flatlays/editorial-magazine/editorial-magazine-024.png",
        "title": "Editorial Magazine 024",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-6",
        "url": "/flatlays/editorial-magazine/editorial-magazine-025.png",
        "title": "Editorial Magazine 025",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-7",
        "url": "/flatlays/editorial-magazine/editorial-magazine-026.png",
        "title": "Editorial Magazine 026",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-8",
        "url": "/flatlays/editorial-magazine/editorial-magazine-027.png",
        "title": "Editorial Magazine 027",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-9",
        "url": "/flatlays/editorial-magazine/editorial-magazine-028.png",
        "title": "Editorial Magazine 028",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-10",
        "url": "/flatlays/editorial-magazine/editorial-magazine-029.png",
        "title": "Editorial Magazine 029",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-11",
        "url": "/flatlays/editorial-magazine/editorial-magazine-030.png",
        "title": "Editorial Magazine 030",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-12",
        "url": "/flatlays/editorial-magazine/editorial-magazine-031.png",
        "title": "Editorial Magazine 031",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-13",
        "url": "/flatlays/editorial-magazine/editorial-magazine-032.png",
        "title": "Editorial Magazine 032",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-14",
        "url": "/flatlays/editorial-magazine/editorial-magazine-033.png",
        "title": "Editorial Magazine 033",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-15",
        "url": "/flatlays/editorial-magazine/editorial-magazine-034.png",
        "title": "Editorial Magazine 034",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-16",
        "url": "/flatlays/editorial-magazine/editorial-magazine-035.png",
        "title": "Editorial Magazine 035",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-17",
        "url": "/flatlays/editorial-magazine/editorial-magazine-036.png",
        "title": "Editorial Magazine 036",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-18",
        "url": "/flatlays/editorial-magazine/editorial-magazine-037.png",
        "title": "Editorial Magazine 037",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-19",
        "url": "/flatlays/editorial-magazine/editorial-magazine-038.png",
        "title": "Editorial Magazine 038",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-20",
        "url": "/flatlays/editorial-magazine/editorial-magazine-039.png",
        "title": "Editorial Magazine 039",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-21",
        "url": "/flatlays/editorial-magazine/editorial-magazine-040.png",
        "title": "Editorial Magazine 040",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-22",
        "url": "/flatlays/editorial-magazine/editorial-magazine-041.png",
        "title": "Editorial Magazine 041",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-23",
        "url": "/flatlays/editorial-magazine/editorial-magazine-042.png",
        "title": "Editorial Magazine 042",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-24",
        "url": "/flatlays/editorial-magazine/editorial-magazine-043.png",
        "title": "Editorial Magazine 043",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-25",
        "url": "/flatlays/editorial-magazine/editorial-magazine-044.png",
        "title": "Editorial Magazine 044",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-26",
        "url": "/flatlays/editorial-magazine/editorial-magazine-045.png",
        "title": "Editorial Magazine 045",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-27",
        "url": "/flatlays/editorial-magazine/editorial-magazine-046.png",
        "title": "Editorial Magazine 046",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-28",
        "url": "/flatlays/editorial-magazine/editorial-magazine-047.png",
        "title": "Editorial Magazine 047",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-29",
        "url": "/flatlays/editorial-magazine/editorial-magazine-048.png",
        "title": "Editorial Magazine 048",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-30",
        "url": "/flatlays/editorial-magazine/editorial-magazine-049.png",
        "title": "Editorial Magazine 049",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-31",
        "url": "/flatlays/editorial-magazine/editorial-magazine-050.png",
        "title": "Editorial Magazine 050",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-32",
        "url": "/flatlays/editorial-magazine/editorial-magazine-051.png",
        "title": "Editorial Magazine 051",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-33",
        "url": "/flatlays/editorial-magazine/editorial-magazine-052.png",
        "title": "Editorial Magazine 052",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-34",
        "url": "/flatlays/editorial-magazine/editorial-magazine-053.png",
        "title": "Editorial Magazine 053",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-35",
        "url": "/flatlays/editorial-magazine/editorial-magazine-054.png",
        "title": "Editorial Magazine 054",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-36",
        "url": "/flatlays/editorial-magazine/editorial-magazine-055.png",
        "title": "Editorial Magazine 055",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-37",
        "url": "/flatlays/editorial-magazine/editorial-magazine-056.png",
        "title": "Editorial Magazine 056",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-38",
        "url": "/flatlays/editorial-magazine/editorial-magazine-057.png",
        "title": "Editorial Magazine 057",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-39",
        "url": "/flatlays/editorial-magazine/editorial-magazine-058.png",
        "title": "Editorial Magazine 058",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-40",
        "url": "/flatlays/editorial-magazine/editorial-magazine-059.png",
        "title": "Editorial Magazine 059",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-41",
        "url": "/flatlays/editorial-magazine/editorial-magazine-060.png",
        "title": "Editorial Magazine 060",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-42",
        "url": "/flatlays/editorial-magazine/editorial-magazine-061.png",
        "title": "Editorial Magazine 061",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-43",
        "url": "/flatlays/editorial-magazine/editorial-magazine-062.png",
        "title": "Editorial Magazine 062",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-44",
        "url": "/flatlays/editorial-magazine/editorial-magazine-063.png",
        "title": "Editorial Magazine 063",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-45",
        "url": "/flatlays/editorial-magazine/editorial-magazine-064.png",
        "title": "Editorial Magazine 064",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-46",
        "url": "/flatlays/editorial-magazine/editorial-magazine-065.png",
        "title": "Editorial Magazine 065",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-47",
        "url": "/flatlays/editorial-magazine/editorial-magazine-066.png",
        "title": "Editorial Magazine 066",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-48",
        "url": "/flatlays/editorial-magazine/editorial-magazine-067.png",
        "title": "Editorial Magazine 067",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-49",
        "url": "/flatlays/editorial-magazine/editorial-magazine-068.png",
        "title": "Editorial Magazine 068",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-50",
        "url": "/flatlays/editorial-magazine/editorial-magazine-069.png",
        "title": "Editorial Magazine 069",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-51",
        "url": "/flatlays/editorial-magazine/editorial-magazine-070.png",
        "title": "Editorial Magazine 070",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-52",
        "url": "/flatlays/editorial-magazine/editorial-magazine-071.png",
        "title": "Editorial Magazine 071",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-53",
        "url": "/flatlays/editorial-magazine/editorial-magazine-072.png",
        "title": "Editorial Magazine 072",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-54",
        "url": "/flatlays/editorial-magazine/editorial-magazine-073.png",
        "title": "Editorial Magazine 073",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-55",
        "url": "/flatlays/editorial-magazine/editorial-magazine-074.png",
        "title": "Editorial Magazine 074",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-56",
        "url": "/flatlays/editorial-magazine/editorial-magazine-075.png",
        "title": "Editorial Magazine 075",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-57",
        "url": "/flatlays/editorial-magazine/editorial-magazine-076.png",
        "title": "Editorial Magazine 076",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-58",
        "url": "/flatlays/editorial-magazine/editorial-magazine-077.png",
        "title": "Editorial Magazine 077",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-59",
        "url": "/flatlays/editorial-magazine/editorial-magazine-078.png",
        "title": "Editorial Magazine 078",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-60",
        "url": "/flatlays/editorial-magazine/editorial-magazine-079.png",
        "title": "Editorial Magazine 079",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-61",
        "url": "/flatlays/editorial-magazine/editorial-magazine-080.png",
        "title": "Editorial Magazine 080",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-62",
        "url": "/flatlays/editorial-magazine/editorial-magazine-081.png",
        "title": "Editorial Magazine 081",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-63",
        "url": "/flatlays/editorial-magazine/editorial-magazine-082.png",
        "title": "Editorial Magazine 082",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-64",
        "url": "/flatlays/editorial-magazine/editorial-magazine-083.png",
        "title": "Editorial Magazine 083",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-65",
        "url": "/flatlays/editorial-magazine/editorial-magazine-084.png",
        "title": "Editorial Magazine 084",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-66",
        "url": "/flatlays/editorial-magazine/editorial-magazine-085.png",
        "title": "Editorial Magazine 085",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-67",
        "url": "/flatlays/editorial-magazine/editorial-magazine-086.png",
        "title": "Editorial Magazine 086",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-68",
        "url": "/flatlays/editorial-magazine/editorial-magazine-087.png",
        "title": "Editorial Magazine 087",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-69",
        "url": "/flatlays/editorial-magazine/editorial-magazine-088.png",
        "title": "Editorial Magazine 088",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-70",
        "url": "/flatlays/editorial-magazine/editorial-magazine-089.png",
        "title": "Editorial Magazine 089",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-71",
        "url": "/flatlays/editorial-magazine/editorial-magazine-090.png",
        "title": "Editorial Magazine 090",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-72",
        "url": "/flatlays/editorial-magazine/editorial-magazine-091.png",
        "title": "Editorial Magazine 091",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-73",
        "url": "/flatlays/editorial-magazine/editorial-magazine-092.png",
        "title": "Editorial Magazine 092",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-74",
        "url": "/flatlays/editorial-magazine/editorial-magazine-093.png",
        "title": "Editorial Magazine 093",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-75",
        "url": "/flatlays/editorial-magazine/editorial-magazine-094.png",
        "title": "Editorial Magazine 094",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-76",
        "url": "/flatlays/editorial-magazine/editorial-magazine-095.png",
        "title": "Editorial Magazine 095",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-77",
        "url": "/flatlays/editorial-magazine/editorial-magazine-096.png",
        "title": "Editorial Magazine 096",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-78",
        "url": "/flatlays/editorial-magazine/editorial-magazine-097.png",
        "title": "Editorial Magazine 097",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-79",
        "url": "/flatlays/editorial-magazine/editorial-magazine-098.png",
        "title": "Editorial Magazine 098",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-80",
        "url": "/flatlays/editorial-magazine/editorial-magazine-099.png",
        "title": "Editorial Magazine 099",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      },
      {
        "id": "editorial-magazine-81",
        "url": "/flatlays/editorial-magazine/editorial-magazine-100.png",
        "title": "Editorial Magazine 100",
        "category": "Editorial Magazine",
        "description": "Editorial Magazine lifestyle flatlay"
      }
    ]
  },
  {
    "id": "european-luxury",
    "name": "European Luxury",
    "description": "Rich textures, warm tones, and sophisticated European styling",
    "aesthetic": "Sophisticated European elegance with warm undertones",
    "backgroundImage": "/flatlays/european-luxury/european-luxury-101.png",
    "colors": [
      "#8b7355",
      "#d4c4a8",
      "#ffffff",
      "#2c2416",
      "#a0956b"
    ],
    "fonts": [
      "Times New Roman",
      "Cormorant Garamond",
      "Libre Baskerville"
    ],
    "images": [
      {
        "id": "european-luxury-1",
        "url": "/flatlays/european-luxury/european-luxury-101.png",
        "title": "European Luxury 101",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-2",
        "url": "/flatlays/european-luxury/european-luxury-102.png",
        "title": "European Luxury 102",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-3",
        "url": "/flatlays/european-luxury/european-luxury-103.png",
        "title": "European Luxury 103",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-4",
        "url": "/flatlays/european-luxury/european-luxury-104.png",
        "title": "European Luxury 104",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-5",
        "url": "/flatlays/european-luxury/european-luxury-105.png",
        "title": "European Luxury 105",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-6",
        "url": "/flatlays/european-luxury/european-luxury-106.png",
        "title": "European Luxury 106",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-7",
        "url": "/flatlays/european-luxury/european-luxury-107.png",
        "title": "European Luxury 107",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-8",
        "url": "/flatlays/european-luxury/european-luxury-108.png",
        "title": "European Luxury 108",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-9",
        "url": "/flatlays/european-luxury/european-luxury-109.png",
        "title": "European Luxury 109",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-10",
        "url": "/flatlays/european-luxury/european-luxury-110.png",
        "title": "European Luxury 110",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-11",
        "url": "/flatlays/european-luxury/european-luxury-111.png",
        "title": "European Luxury 111",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-12",
        "url": "/flatlays/european-luxury/european-luxury-112.png",
        "title": "European Luxury 112",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-13",
        "url": "/flatlays/european-luxury/european-luxury-113.png",
        "title": "European Luxury 113",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-14",
        "url": "/flatlays/european-luxury/european-luxury-114.png",
        "title": "European Luxury 114",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-15",
        "url": "/flatlays/european-luxury/european-luxury-115.png",
        "title": "European Luxury 115",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-16",
        "url": "/flatlays/european-luxury/european-luxury-116.png",
        "title": "European Luxury 116",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-17",
        "url": "/flatlays/european-luxury/european-luxury-117.png",
        "title": "European Luxury 117",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-18",
        "url": "/flatlays/european-luxury/european-luxury-118.png",
        "title": "European Luxury 118",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-19",
        "url": "/flatlays/european-luxury/european-luxury-119.png",
        "title": "European Luxury 119",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-20",
        "url": "/flatlays/european-luxury/european-luxury-120.png",
        "title": "European Luxury 120",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-21",
        "url": "/flatlays/european-luxury/european-luxury-121.png",
        "title": "European Luxury 121",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-22",
        "url": "/flatlays/european-luxury/european-luxury-122.png",
        "title": "European Luxury 122",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-23",
        "url": "/flatlays/european-luxury/european-luxury-123.png",
        "title": "European Luxury 123",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-24",
        "url": "/flatlays/european-luxury/european-luxury-124.png",
        "title": "European Luxury 124",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-25",
        "url": "/flatlays/european-luxury/european-luxury-125.png",
        "title": "European Luxury 125",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-26",
        "url": "/flatlays/european-luxury/european-luxury-126.png",
        "title": "European Luxury 126",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-27",
        "url": "/flatlays/european-luxury/european-luxury-127.png",
        "title": "European Luxury 127",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-28",
        "url": "/flatlays/european-luxury/european-luxury-128.png",
        "title": "European Luxury 128",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-29",
        "url": "/flatlays/european-luxury/european-luxury-129.png",
        "title": "European Luxury 129",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-30",
        "url": "/flatlays/european-luxury/european-luxury-130.png",
        "title": "European Luxury 130",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-31",
        "url": "/flatlays/european-luxury/european-luxury-131.png",
        "title": "European Luxury 131",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-32",
        "url": "/flatlays/european-luxury/european-luxury-132.png",
        "title": "European Luxury 132",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-33",
        "url": "/flatlays/european-luxury/european-luxury-133.png",
        "title": "European Luxury 133",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-34",
        "url": "/flatlays/european-luxury/european-luxury-134.png",
        "title": "European Luxury 134",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-35",
        "url": "/flatlays/european-luxury/european-luxury-135.png",
        "title": "European Luxury 135",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-36",
        "url": "/flatlays/european-luxury/european-luxury-136.png",
        "title": "European Luxury 136",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-37",
        "url": "/flatlays/european-luxury/european-luxury-137.png",
        "title": "European Luxury 137",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-38",
        "url": "/flatlays/european-luxury/european-luxury-138.png",
        "title": "European Luxury 138",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-39",
        "url": "/flatlays/european-luxury/european-luxury-139.png",
        "title": "European Luxury 139",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-40",
        "url": "/flatlays/european-luxury/european-luxury-140.png",
        "title": "European Luxury 140",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-41",
        "url": "/flatlays/european-luxury/european-luxury-141.png",
        "title": "European Luxury 141",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-42",
        "url": "/flatlays/european-luxury/european-luxury-142.png",
        "title": "European Luxury 142",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-43",
        "url": "/flatlays/european-luxury/european-luxury-143.png",
        "title": "European Luxury 143",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-44",
        "url": "/flatlays/european-luxury/european-luxury-144.png",
        "title": "European Luxury 144",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-45",
        "url": "/flatlays/european-luxury/european-luxury-145.png",
        "title": "European Luxury 145",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-46",
        "url": "/flatlays/european-luxury/european-luxury-146.png",
        "title": "European Luxury 146",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-47",
        "url": "/flatlays/european-luxury/european-luxury-147.png",
        "title": "European Luxury 147",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-48",
        "url": "/flatlays/european-luxury/european-luxury-148.png",
        "title": "European Luxury 148",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-49",
        "url": "/flatlays/european-luxury/european-luxury-149.png",
        "title": "European Luxury 149",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      },
      {
        "id": "european-luxury-50",
        "url": "/flatlays/european-luxury/european-luxury-150.png",
        "title": "European Luxury 150",
        "category": "European Luxury",
        "description": "European Luxury lifestyle flatlay"
      }
    ]
  },
  {
    "id": "business-professional",
    "name": "Business Professional",
    "description": "Clean corporate styling with professional accessories and neutral tones",
    "aesthetic": "Professional sophistication with clean lines",
    "backgroundImage": "/flatlays/business-professional/business-professional-201.png",
    "colors": [
      "#ffffff",
      "#f8f9fa",
      "#000000",
      "#495057",
      "#6c757d"
    ],
    "fonts": [
      "Times New Roman",
      "Source Sans Pro",
      "Roboto"
    ],
    "images": [
      {
        "id": "business-professional-1",
        "url": "/flatlays/business-professional/business-professional-201.png",
        "title": "Business Professional 201",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-2",
        "url": "/flatlays/business-professional/business-professional-202.png",
        "title": "Business Professional 202",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-3",
        "url": "/flatlays/business-professional/business-professional-203.png",
        "title": "Business Professional 203",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-4",
        "url": "/flatlays/business-professional/business-professional-204.png",
        "title": "Business Professional 204",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-5",
        "url": "/flatlays/business-professional/business-professional-205.png",
        "title": "Business Professional 205",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-6",
        "url": "/flatlays/business-professional/business-professional-206.png",
        "title": "Business Professional 206",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-7",
        "url": "/flatlays/business-professional/business-professional-207.png",
        "title": "Business Professional 207",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-8",
        "url": "/flatlays/business-professional/business-professional-208.png",
        "title": "Business Professional 208",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-9",
        "url": "/flatlays/business-professional/business-professional-209.png",
        "title": "Business Professional 209",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-10",
        "url": "/flatlays/business-professional/business-professional-210.png",
        "title": "Business Professional 210",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-11",
        "url": "/flatlays/business-professional/business-professional-211.png",
        "title": "Business Professional 211",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-12",
        "url": "/flatlays/business-professional/business-professional-212.png",
        "title": "Business Professional 212",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-13",
        "url": "/flatlays/business-professional/business-professional-213.png",
        "title": "Business Professional 213",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-14",
        "url": "/flatlays/business-professional/business-professional-214.png",
        "title": "Business Professional 214",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-15",
        "url": "/flatlays/business-professional/business-professional-215.png",
        "title": "Business Professional 215",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-16",
        "url": "/flatlays/business-professional/business-professional-216.png",
        "title": "Business Professional 216",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-17",
        "url": "/flatlays/business-professional/business-professional-217.png",
        "title": "Business Professional 217",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-18",
        "url": "/flatlays/business-professional/business-professional-218.png",
        "title": "Business Professional 218",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-19",
        "url": "/flatlays/business-professional/business-professional-219.png",
        "title": "Business Professional 219",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-20",
        "url": "/flatlays/business-professional/business-professional-220.png",
        "title": "Business Professional 220",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-21",
        "url": "/flatlays/business-professional/business-professional-221.png",
        "title": "Business Professional 221",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-22",
        "url": "/flatlays/business-professional/business-professional-222.png",
        "title": "Business Professional 222",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-23",
        "url": "/flatlays/business-professional/business-professional-223.png",
        "title": "Business Professional 223",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-24",
        "url": "/flatlays/business-professional/business-professional-224.png",
        "title": "Business Professional 224",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-25",
        "url": "/flatlays/business-professional/business-professional-225.png",
        "title": "Business Professional 225",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-26",
        "url": "/flatlays/business-professional/business-professional-226.png",
        "title": "Business Professional 226",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-27",
        "url": "/flatlays/business-professional/business-professional-227.png",
        "title": "Business Professional 227",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-28",
        "url": "/flatlays/business-professional/business-professional-228.png",
        "title": "Business Professional 228",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-29",
        "url": "/flatlays/business-professional/business-professional-229.png",
        "title": "Business Professional 229",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-30",
        "url": "/flatlays/business-professional/business-professional-230.png",
        "title": "Business Professional 230",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-31",
        "url": "/flatlays/business-professional/business-professional-231.png",
        "title": "Business Professional 231",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-32",
        "url": "/flatlays/business-professional/business-professional-232.png",
        "title": "Business Professional 232",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-33",
        "url": "/flatlays/business-professional/business-professional-233.png",
        "title": "Business Professional 233",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-34",
        "url": "/flatlays/business-professional/business-professional-234.png",
        "title": "Business Professional 234",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-35",
        "url": "/flatlays/business-professional/business-professional-235.png",
        "title": "Business Professional 235",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-36",
        "url": "/flatlays/business-professional/business-professional-236.png",
        "title": "Business Professional 236",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-37",
        "url": "/flatlays/business-professional/business-professional-237.png",
        "title": "Business Professional 237",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-38",
        "url": "/flatlays/business-professional/business-professional-238.png",
        "title": "Business Professional 238",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-39",
        "url": "/flatlays/business-professional/business-professional-239.png",
        "title": "Business Professional 239",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-40",
        "url": "/flatlays/business-professional/business-professional-240.png",
        "title": "Business Professional 240",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-41",
        "url": "/flatlays/business-professional/business-professional-241.png",
        "title": "Business Professional 241",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-42",
        "url": "/flatlays/business-professional/business-professional-242.png",
        "title": "Business Professional 242",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-43",
        "url": "/flatlays/business-professional/business-professional-243.png",
        "title": "Business Professional 243",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-44",
        "url": "/flatlays/business-professional/business-professional-244.png",
        "title": "Business Professional 244",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-45",
        "url": "/flatlays/business-professional/business-professional-245.png",
        "title": "Business Professional 245",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-46",
        "url": "/flatlays/business-professional/business-professional-246.png",
        "title": "Business Professional 246",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-47",
        "url": "/flatlays/business-professional/business-professional-247.png",
        "title": "Business Professional 247",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-48",
        "url": "/flatlays/business-professional/business-professional-248.png",
        "title": "Business Professional 248",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-49",
        "url": "/flatlays/business-professional/business-professional-249.png",
        "title": "Business Professional 249",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      },
      {
        "id": "business-professional-50",
        "url": "/flatlays/business-professional/business-professional-250.png",
        "title": "Business Professional 250",
        "category": "Business Professional",
        "description": "Business Professional lifestyle flatlay"
      }
    ]
  },
  {
    "id": "wellness-mindset",
    "name": "Wellness Mindset",
    "description": "Calm natural elements, wellness products, and mindful living aesthetics",
    "aesthetic": "Peaceful wellness with natural elements",
    "backgroundImage": "/flatlays/wellness-mindset/wellness-mindset-151.png",
    "colors": [
      "#e8f5e8",
      "#a8d8a8",
      "#ffffff",
      "#6b8e6b",
      "#4a6741"
    ],
    "fonts": [
      "Times New Roman",
      "Lato",
      "Open Sans"
    ],
    "images": [
      {
        "id": "wellness-mindset-1",
        "url": "/flatlays/wellness-mindset/wellness-mindset-151.png",
        "title": "Wellness Mindset 151",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-2",
        "url": "/flatlays/wellness-mindset/wellness-mindset-152.png",
        "title": "Wellness Mindset 152",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-3",
        "url": "/flatlays/wellness-mindset/wellness-mindset-153.png",
        "title": "Wellness Mindset 153",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-4",
        "url": "/flatlays/wellness-mindset/wellness-mindset-154.png",
        "title": "Wellness Mindset 154",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-5",
        "url": "/flatlays/wellness-mindset/wellness-mindset-155.png",
        "title": "Wellness Mindset 155",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-6",
        "url": "/flatlays/wellness-mindset/wellness-mindset-156.png",
        "title": "Wellness Mindset 156",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-7",
        "url": "/flatlays/wellness-mindset/wellness-mindset-157.png",
        "title": "Wellness Mindset 157",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-8",
        "url": "/flatlays/wellness-mindset/wellness-mindset-158.png",
        "title": "Wellness Mindset 158",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-9",
        "url": "/flatlays/wellness-mindset/wellness-mindset-159.png",
        "title": "Wellness Mindset 159",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-10",
        "url": "/flatlays/wellness-mindset/wellness-mindset-160.png",
        "title": "Wellness Mindset 160",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-11",
        "url": "/flatlays/wellness-mindset/wellness-mindset-161.png",
        "title": "Wellness Mindset 161",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-12",
        "url": "/flatlays/wellness-mindset/wellness-mindset-162.png",
        "title": "Wellness Mindset 162",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-13",
        "url": "/flatlays/wellness-mindset/wellness-mindset-163.png",
        "title": "Wellness Mindset 163",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-14",
        "url": "/flatlays/wellness-mindset/wellness-mindset-164.png",
        "title": "Wellness Mindset 164",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-15",
        "url": "/flatlays/wellness-mindset/wellness-mindset-165.png",
        "title": "Wellness Mindset 165",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-16",
        "url": "/flatlays/wellness-mindset/wellness-mindset-166.png",
        "title": "Wellness Mindset 166",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-17",
        "url": "/flatlays/wellness-mindset/wellness-mindset-167.png",
        "title": "Wellness Mindset 167",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-18",
        "url": "/flatlays/wellness-mindset/wellness-mindset-168.png",
        "title": "Wellness Mindset 168",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-19",
        "url": "/flatlays/wellness-mindset/wellness-mindset-169.png",
        "title": "Wellness Mindset 169",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-20",
        "url": "/flatlays/wellness-mindset/wellness-mindset-170.png",
        "title": "Wellness Mindset 170",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-21",
        "url": "/flatlays/wellness-mindset/wellness-mindset-171.png",
        "title": "Wellness Mindset 171",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-22",
        "url": "/flatlays/wellness-mindset/wellness-mindset-172.png",
        "title": "Wellness Mindset 172",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-23",
        "url": "/flatlays/wellness-mindset/wellness-mindset-173.png",
        "title": "Wellness Mindset 173",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-24",
        "url": "/flatlays/wellness-mindset/wellness-mindset-174.png",
        "title": "Wellness Mindset 174",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-25",
        "url": "/flatlays/wellness-mindset/wellness-mindset-175.png",
        "title": "Wellness Mindset 175",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-26",
        "url": "/flatlays/wellness-mindset/wellness-mindset-176.png",
        "title": "Wellness Mindset 176",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-27",
        "url": "/flatlays/wellness-mindset/wellness-mindset-177.png",
        "title": "Wellness Mindset 177",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-28",
        "url": "/flatlays/wellness-mindset/wellness-mindset-178.png",
        "title": "Wellness Mindset 178",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-29",
        "url": "/flatlays/wellness-mindset/wellness-mindset-179.png",
        "title": "Wellness Mindset 179",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-30",
        "url": "/flatlays/wellness-mindset/wellness-mindset-180.png",
        "title": "Wellness Mindset 180",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-31",
        "url": "/flatlays/wellness-mindset/wellness-mindset-181.png",
        "title": "Wellness Mindset 181",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-32",
        "url": "/flatlays/wellness-mindset/wellness-mindset-182.png",
        "title": "Wellness Mindset 182",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-33",
        "url": "/flatlays/wellness-mindset/wellness-mindset-183.png",
        "title": "Wellness Mindset 183",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-34",
        "url": "/flatlays/wellness-mindset/wellness-mindset-184.png",
        "title": "Wellness Mindset 184",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-35",
        "url": "/flatlays/wellness-mindset/wellness-mindset-185.png",
        "title": "Wellness Mindset 185",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-36",
        "url": "/flatlays/wellness-mindset/wellness-mindset-186.png",
        "title": "Wellness Mindset 186",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-37",
        "url": "/flatlays/wellness-mindset/wellness-mindset-187.png",
        "title": "Wellness Mindset 187",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-38",
        "url": "/flatlays/wellness-mindset/wellness-mindset-188.png",
        "title": "Wellness Mindset 188",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-39",
        "url": "/flatlays/wellness-mindset/wellness-mindset-189.png",
        "title": "Wellness Mindset 189",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-40",
        "url": "/flatlays/wellness-mindset/wellness-mindset-190.png",
        "title": "Wellness Mindset 190",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-41",
        "url": "/flatlays/wellness-mindset/wellness-mindset-191.png",
        "title": "Wellness Mindset 191",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-42",
        "url": "/flatlays/wellness-mindset/wellness-mindset-192.png",
        "title": "Wellness Mindset 192",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-43",
        "url": "/flatlays/wellness-mindset/wellness-mindset-193.png",
        "title": "Wellness Mindset 193",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-44",
        "url": "/flatlays/wellness-mindset/wellness-mindset-194.png",
        "title": "Wellness Mindset 194",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-45",
        "url": "/flatlays/wellness-mindset/wellness-mindset-195.png",
        "title": "Wellness Mindset 195",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-46",
        "url": "/flatlays/wellness-mindset/wellness-mindset-196.png",
        "title": "Wellness Mindset 196",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-47",
        "url": "/flatlays/wellness-mindset/wellness-mindset-197.png",
        "title": "Wellness Mindset 197",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-48",
        "url": "/flatlays/wellness-mindset/wellness-mindset-198.png",
        "title": "Wellness Mindset 198",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-49",
        "url": "/flatlays/wellness-mindset/wellness-mindset-199.png",
        "title": "Wellness Mindset 199",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      },
      {
        "id": "wellness-mindset-50",
        "url": "/flatlays/wellness-mindset/wellness-mindset-200.png",
        "title": "Wellness Mindset 200",
        "category": "Wellness Mindset",
        "description": "Wellness Mindset lifestyle flatlay"
      }
    ]
  },
  {
    "id": "pink-girly",
    "name": "Pink and Girly",
    "description": "Feminine pink aesthetic with girly accessories and soft textures",
    "aesthetic": "Sweet feminine charm with playful pink tones",
    "backgroundImage": "/flatlays/pink-girly/pink-girly-251.png",
    "colors": [
      "#ffc0cb",
      "#ffb6c1",
      "#f0f0f0",
      "#ffffff",
      "#ff69b4"
    ],
    "fonts": [
      "Times New Roman",
      "Playfair Display",
      "Dancing Script"
    ],
    "images": [
      {
        "id": "pink-girly-1",
        "url": "/flatlays/pink-girly/pink-girly-251.png",
        "title": "Pink Girly 251",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-2",
        "url": "/flatlays/pink-girly/pink-girly-252.png",
        "title": "Pink Girly 252",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-3",
        "url": "/flatlays/pink-girly/pink-girly-253.png",
        "title": "Pink Girly 253",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-4",
        "url": "/flatlays/pink-girly/pink-girly-254.png",
        "title": "Pink Girly 254",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-5",
        "url": "/flatlays/pink-girly/pink-girly-255.png",
        "title": "Pink Girly 255",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-6",
        "url": "/flatlays/pink-girly/pink-girly-256.png",
        "title": "Pink Girly 256",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-7",
        "url": "/flatlays/pink-girly/pink-girly-257.png",
        "title": "Pink Girly 257",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-8",
        "url": "/flatlays/pink-girly/pink-girly-258.png",
        "title": "Pink Girly 258",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-9",
        "url": "/flatlays/pink-girly/pink-girly-259.png",
        "title": "Pink Girly 259",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-10",
        "url": "/flatlays/pink-girly/pink-girly-260.png",
        "title": "Pink Girly 260",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-11",
        "url": "/flatlays/pink-girly/pink-girly-261.png",
        "title": "Pink Girly 261",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-12",
        "url": "/flatlays/pink-girly/pink-girly-262.png",
        "title": "Pink Girly 262",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-13",
        "url": "/flatlays/pink-girly/pink-girly-263.png",
        "title": "Pink Girly 263",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-14",
        "url": "/flatlays/pink-girly/pink-girly-264.png",
        "title": "Pink Girly 264",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-15",
        "url": "/flatlays/pink-girly/pink-girly-265.png",
        "title": "Pink Girly 265",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-16",
        "url": "/flatlays/pink-girly/pink-girly-266.png",
        "title": "Pink Girly 266",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-17",
        "url": "/flatlays/pink-girly/pink-girly-267.png",
        "title": "Pink Girly 267",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-18",
        "url": "/flatlays/pink-girly/pink-girly-268.png",
        "title": "Pink Girly 268",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-19",
        "url": "/flatlays/pink-girly/pink-girly-269.png",
        "title": "Pink Girly 269",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-20",
        "url": "/flatlays/pink-girly/pink-girly-270.png",
        "title": "Pink Girly 270",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-21",
        "url": "/flatlays/pink-girly/pink-girly-271.png",
        "title": "Pink Girly 271",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-22",
        "url": "/flatlays/pink-girly/pink-girly-272.png",
        "title": "Pink Girly 272",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-23",
        "url": "/flatlays/pink-girly/pink-girly-273.png",
        "title": "Pink Girly 273",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-24",
        "url": "/flatlays/pink-girly/pink-girly-274.png",
        "title": "Pink Girly 274",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-25",
        "url": "/flatlays/pink-girly/pink-girly-275.png",
        "title": "Pink Girly 275",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-26",
        "url": "/flatlays/pink-girly/pink-girly-276.png",
        "title": "Pink Girly 276",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-27",
        "url": "/flatlays/pink-girly/pink-girly-277.png",
        "title": "Pink Girly 277",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-28",
        "url": "/flatlays/pink-girly/pink-girly-278.png",
        "title": "Pink Girly 278",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-29",
        "url": "/flatlays/pink-girly/pink-girly-279.png",
        "title": "Pink Girly 279",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-30",
        "url": "/flatlays/pink-girly/pink-girly-280.png",
        "title": "Pink Girly 280",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-31",
        "url": "/flatlays/pink-girly/pink-girly-281.png",
        "title": "Pink Girly 281",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-32",
        "url": "/flatlays/pink-girly/pink-girly-282.png",
        "title": "Pink Girly 282",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-33",
        "url": "/flatlays/pink-girly/pink-girly-283.png",
        "title": "Pink Girly 283",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-34",
        "url": "/flatlays/pink-girly/pink-girly-284.png",
        "title": "Pink Girly 284",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-35",
        "url": "/flatlays/pink-girly/pink-girly-285.png",
        "title": "Pink Girly 285",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-36",
        "url": "/flatlays/pink-girly/pink-girly-286.png",
        "title": "Pink Girly 286",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-37",
        "url": "/flatlays/pink-girly/pink-girly-287.png",
        "title": "Pink Girly 287",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-38",
        "url": "/flatlays/pink-girly/pink-girly-288.png",
        "title": "Pink Girly 288",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-39",
        "url": "/flatlays/pink-girly/pink-girly-289.png",
        "title": "Pink Girly 289",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-40",
        "url": "/flatlays/pink-girly/pink-girly-290.png",
        "title": "Pink Girly 290",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-41",
        "url": "/flatlays/pink-girly/pink-girly-291.png",
        "title": "Pink Girly 291",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-42",
        "url": "/flatlays/pink-girly/pink-girly-292.png",
        "title": "Pink Girly 292",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-43",
        "url": "/flatlays/pink-girly/pink-girly-293.png",
        "title": "Pink Girly 293",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-44",
        "url": "/flatlays/pink-girly/pink-girly-294.png",
        "title": "Pink Girly 294",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-45",
        "url": "/flatlays/pink-girly/pink-girly-295.png",
        "title": "Pink Girly 295",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-46",
        "url": "/flatlays/pink-girly/pink-girly-296.png",
        "title": "Pink Girly 296",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-47",
        "url": "/flatlays/pink-girly/pink-girly-297.png",
        "title": "Pink Girly 297",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-48",
        "url": "/flatlays/pink-girly/pink-girly-298.png",
        "title": "Pink Girly 298",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-49",
        "url": "/flatlays/pink-girly/pink-girly-299.png",
        "title": "Pink Girly 299",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-50",
        "url": "/flatlays/pink-girly/pink-girly-300.png",
        "title": "Pink Girly 300",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-51",
        "url": "/flatlays/pink-girly/pink-girly-301.png",
        "title": "Pink Girly 301",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-52",
        "url": "/flatlays/pink-girly/pink-girly-302.png",
        "title": "Pink Girly 302",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-53",
        "url": "/flatlays/pink-girly/pink-girly-303.png",
        "title": "Pink Girly 303",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-54",
        "url": "/flatlays/pink-girly/pink-girly-304.png",
        "title": "Pink Girly 304",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-55",
        "url": "/flatlays/pink-girly/pink-girly-305.png",
        "title": "Pink Girly 305",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-56",
        "url": "/flatlays/pink-girly/pink-girly-306.png",
        "title": "Pink Girly 306",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-57",
        "url": "/flatlays/pink-girly/pink-girly-307.png",
        "title": "Pink Girly 307",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-58",
        "url": "/flatlays/pink-girly/pink-girly-308.png",
        "title": "Pink Girly 308",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-59",
        "url": "/flatlays/pink-girly/pink-girly-309.png",
        "title": "Pink Girly 309",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-60",
        "url": "/flatlays/pink-girly/pink-girly-310.png",
        "title": "Pink Girly 310",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-61",
        "url": "/flatlays/pink-girly/pink-girly-311.png",
        "title": "Pink Girly 311",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-62",
        "url": "/flatlays/pink-girly/pink-girly-312.png",
        "title": "Pink Girly 312",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-63",
        "url": "/flatlays/pink-girly/pink-girly-313.png",
        "title": "Pink Girly 313",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-64",
        "url": "/flatlays/pink-girly/pink-girly-314.png",
        "title": "Pink Girly 314",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-65",
        "url": "/flatlays/pink-girly/pink-girly-315.png",
        "title": "Pink Girly 315",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-66",
        "url": "/flatlays/pink-girly/pink-girly-316.png",
        "title": "Pink Girly 316",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-67",
        "url": "/flatlays/pink-girly/pink-girly-317.png",
        "title": "Pink Girly 317",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-68",
        "url": "/flatlays/pink-girly/pink-girly-318.png",
        "title": "Pink Girly 318",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-69",
        "url": "/flatlays/pink-girly/pink-girly-319.png",
        "title": "Pink Girly 319",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-70",
        "url": "/flatlays/pink-girly/pink-girly-320.png",
        "title": "Pink Girly 320",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-71",
        "url": "/flatlays/pink-girly/pink-girly-321.png",
        "title": "Pink Girly 321",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-72",
        "url": "/flatlays/pink-girly/pink-girly-322.png",
        "title": "Pink Girly 322",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-73",
        "url": "/flatlays/pink-girly/pink-girly-323.png",
        "title": "Pink Girly 323",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-74",
        "url": "/flatlays/pink-girly/pink-girly-324.png",
        "title": "Pink Girly 324",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-75",
        "url": "/flatlays/pink-girly/pink-girly-325.png",
        "title": "Pink Girly 325",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-76",
        "url": "/flatlays/pink-girly/pink-girly-326.png",
        "title": "Pink Girly 326",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-77",
        "url": "/flatlays/pink-girly/pink-girly-327.png",
        "title": "Pink Girly 327",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-78",
        "url": "/flatlays/pink-girly/pink-girly-328.png",
        "title": "Pink Girly 328",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-79",
        "url": "/flatlays/pink-girly/pink-girly-329.png",
        "title": "Pink Girly 329",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-80",
        "url": "/flatlays/pink-girly/pink-girly-330.png",
        "title": "Pink Girly 330",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-81",
        "url": "/flatlays/pink-girly/pink-girly-331.png",
        "title": "Pink Girly 331",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-82",
        "url": "/flatlays/pink-girly/pink-girly-332.png",
        "title": "Pink Girly 332",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-83",
        "url": "/flatlays/pink-girly/pink-girly-333.png",
        "title": "Pink Girly 333",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-84",
        "url": "/flatlays/pink-girly/pink-girly-334.png",
        "title": "Pink Girly 334",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-85",
        "url": "/flatlays/pink-girly/pink-girly-335.png",
        "title": "Pink Girly 335",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-86",
        "url": "/flatlays/pink-girly/pink-girly-336.png",
        "title": "Pink Girly 336",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-87",
        "url": "/flatlays/pink-girly/pink-girly-337.png",
        "title": "Pink Girly 337",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-88",
        "url": "/flatlays/pink-girly/pink-girly-338.png",
        "title": "Pink Girly 338",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      },
      {
        "id": "pink-girly-89",
        "url": "/flatlays/pink-girly/pink-girly-339.png",
        "title": "Pink Girly 339",
        "category": "Pink and Girly",
        "description": "Pink and Girly lifestyle flatlay"
      }
    ]
  },
  {
    "id": "coastal-vibes",
    "name": "Coastal Vibes",
    "description": "Ocean-inspired flatlays with nautical elements, shells, and beach aesthetics",
    "aesthetic": "Breezy coastal charm with oceanic blues and sandy neutrals",
    "backgroundImage": "/flatlays/luxury-minimal/luxury-minimal-001.png",
    "colors": [
      "#87ceeb",
      "#e0f6ff",
      "#f0f8ff",
      "#ffffff",
      "#20b2aa"
    ],
    "fonts": [
      "Times New Roman",
      "Source Sans Pro",
      "Merriweather"
    ],
    "images": [
      {
        "id": "cv-1",
        "url": "/flatlays/luxury-minimal/luxury-minimal-001.png",
        "title": "Coastal 1",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-2",
        "url": "/flatlays/luxury-minimal/luxury-minimal-002.png",
        "title": "Coastal 2",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-3",
        "url": "/flatlays/luxury-minimal/luxury-minimal-003.png",
        "title": "Coastal 3",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-4",
        "url": "/flatlays/luxury-minimal/luxury-minimal-004.png",
        "title": "Coastal 4",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-5",
        "url": "/flatlays/luxury-minimal/luxury-minimal-005.png",
        "title": "Coastal 5",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-6",
        "url": "/flatlays/luxury-minimal/luxury-minimal-006.png",
        "title": "Coastal 6",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-7",
        "url": "/flatlays/luxury-minimal/luxury-minimal-007.png",
        "title": "Coastal 7",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      },
      {
        "id": "cv-8",
        "url": "/flatlays/luxury-minimal/luxury-minimal-008.png",
        "title": "Coastal 8",
        "category": "Coastal Vibes",
        "description": "Coastal vibes lifestyle flatlay - Coming Soon"
      }
    ]
  },
  {
    "id": "cream-aesthetic",
    "name": "Cream Aesthetic",
    "description": "Warm cream tones with soft textures and cozy minimalist vibes",
    "aesthetic": "Soft sophisticated warmth with creamy neutral tones",
    "backgroundImage": "/flatlays/european-luxury/european-luxury-101.png",
    "colors": [
      "#f5f5dc",
      "#faf0e6",
      "#fff8dc",
      "#ffffff",
      "#deb887"
    ],
    "fonts": [
      "Times New Roman",
      "Libre Baskerville",
      "Lora"
    ],
    "images": [
      {
        "id": "ca-1",
        "url": "/flatlays/european-luxury/european-luxury-101.png",
        "title": "Cream 1",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-2",
        "url": "/flatlays/european-luxury/european-luxury-102.png",
        "title": "Cream 2",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-3",
        "url": "/flatlays/european-luxury/european-luxury-103.png",
        "title": "Cream 3",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-4",
        "url": "/flatlays/european-luxury/european-luxury-104.png",
        "title": "Cream 4",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-5",
        "url": "/flatlays/european-luxury/european-luxury-105.png",
        "title": "Cream 5",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-6",
        "url": "/flatlays/european-luxury/european-luxury-106.png",
        "title": "Cream 6",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-7",
        "url": "/flatlays/european-luxury/european-luxury-107.png",
        "title": "Cream 7",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      },
      {
        "id": "ca-8",
        "url": "/flatlays/european-luxury/european-luxury-108.png",
        "title": "Cream 8",
        "category": "Cream Aesthetic",
        "description": "Cream aesthetic lifestyle flatlay - Coming Soon"
      }
    ]
  }
];
