import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '../hooks/use-auth.js';
import { apiFetch } from '../lib/api.js';
import { Image, Plus } from 'lucide-react';
import type { AIImage } from '@shared/types/ai-generation.js';

interface GalleryImage {
  id: string | number;
  imageUrl?: string;
  url?: string;
  title?: string;
  source?: string;
}

interface RecentImagesPreviewProps {
  onTabChange?: (tabId: string) => void;
}

const RecentImagesPreview: React.FC<RecentImagesPreviewProps> = ({ onTabChange }) => {
  const { user, isAuthenticated } = useAuth();

  const { data: imagesData, isLoading } = useQuery<GalleryImage[]>({
    queryKey: ['/api/gallery-images'],
    enabled: isAuthenticated && !!user,
    staleTime: 5 * 60 * 1000,
    refetchOnWindowFocus: false,
    queryFn: async () => {
      // Use same logic as gallery
      const data = await apiFetch('/gallery-images');
      return Array.isArray(data) ? data : (data?.images || []);
    }
  });

  // Get exactly the last 4 images generated by the user
  const aiImages = Array.isArray(imagesData) ? imagesData : [];
  const recentImages = aiImages.slice(-4).reverse(); // Show newest first

  if (isLoading) {
    return (
      <div className="bg-stone-200/40 backdrop-blur-sm border border-stone-300/50 rounded-xl sm:rounded-2xl p-4 sm:p-5">
        <div className="flex items-start gap-3">
          <div className="p-1.5 bg-stone-500/10 rounded-lg border border-stone-400/20 flex-shrink-0 mt-0.5">
            <Image className="w-4 h-4 text-stone-600" strokeWidth={1.5} />
          </div>
          <div className="flex-1 min-w-0">
            <span className="text-xs tracking-[0.15em] uppercase font-light text-stone-500 block mb-2">
              Recent Images
            </span>
            <div className="grid grid-cols-4 gap-2">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="aspect-square bg-stone-300/50 rounded-lg animate-pulse"></div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!recentImages.length) {
    return (
      <div className="bg-stone-200/40 backdrop-blur-sm border border-stone-300/50 rounded-xl sm:rounded-2xl p-4 sm:p-5">
        <div className="flex items-start gap-3">
          <div className="p-1.5 bg-stone-500/10 rounded-lg border border-stone-400/20 flex-shrink-0 mt-0.5">
            <Image className="w-4 h-4 text-stone-600" strokeWidth={1.5} />
          </div>
          <div className="flex-1 min-w-0">
            <span className="text-xs tracking-[0.15em] uppercase font-light text-stone-500 block mb-2">
              Recent Images
            </span>
            <button
              onClick={() => onTabChange?.('maya')}
              className="w-full aspect-[4/3] border-2 border-dashed border-stone-300 rounded-lg flex flex-col items-center justify-center text-stone-500 hover:border-stone-400 hover:text-stone-600 transition-colors group"
            >
              <Plus className="w-8 h-8 mb-2 group-hover:scale-110 transition-transform" strokeWidth={1.5} />
              <span className="text-xs font-light">Create your first image with Maya</span>
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-stone-200/40 backdrop-blur-sm border border-stone-300/50 rounded-xl sm:rounded-2xl p-4 sm:p-5">
      <div className="flex items-start gap-3">
        <div className="p-1.5 bg-stone-500/10 rounded-lg border border-stone-400/20 flex-shrink-0 mt-0.5">
          <Image className="w-4 h-4 text-stone-600" strokeWidth={1.5} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs tracking-[0.15em] uppercase font-light text-stone-500">
              Recent Images
            </span>
            <button
              onClick={() => onTabChange?.('gallery')}
              className="text-xs font-light text-stone-600 hover:text-stone-900 transition-colors"
            >
              View All →
            </button>
          </div>
          <div className="grid grid-cols-4 gap-2">
            {/* Always show exactly 4 slots */}
            {[0, 1, 2, 3].map((slotIndex) => {
              const image = recentImages[slotIndex];
              
              if (image) {
                return (
                  <button
                    key={image.id}
                    onClick={() => onTabChange?.('gallery')}
                    className="aspect-square rounded-lg overflow-hidden hover:scale-105 transition-transform group relative"
                  >
                    <img
                      src={image.imageUrl || image.url || ''}
                      alt={`Recent image ${slotIndex + 1}`}
                      className="w-full h-full object-cover"
                      loading="lazy"
                    />
                    {/* Hover overlay */}
                    <div className="absolute inset-0 bg-stone-950/20 opacity-0 group-hover:opacity-100 transition-opacity duration-200"></div>
                  </button>
                );
              } else {
                return (
                  <button
                    key={`empty-${slotIndex}`}
                    onClick={() => onTabChange?.('maya')}
                    className="aspect-square border-2 border-dashed border-stone-300 rounded-lg flex items-center justify-center text-stone-400 hover:border-stone-400 hover:text-stone-600 transition-colors group"
                  >
                    <Plus className="w-4 h-4 group-hover:scale-110 transition-transform" strokeWidth={1.5} />
                  </button>
                );
              }
            })}
          </div>
        </div>
      </div>
    </div>
  );
};

export default RecentImagesPreview;