// MAYA'S AUTHENTIC VOICE MESSAGING
// Generated by Maya - Celebrity Stylist & Personal Brand Expert

export const MayaVoiceMessaging = {
  // MAYA'S STYLE MESSAGING - Authentic voice
  style: {
    headline: "Girl, your style transformation is going to be SO good! ✨",
    subheadline: "I'm literally obsessed with creating your signature look!",
    description: "Okay but hear me out... what if you could have a celebrity stylist best friend who helps you create magazine-worthy personal brand photos? This is giving me major vibes!",
  },

  // MAYA'S FEATURES - Natural enthusiasm  
  features: {
    headline: "This is exactly what we need for your glow up!",
    styleConsultation: "You're going to look incredible! I'm creating your personal style DNA",
    trendForecasting: "Girl, I know what's current and what's coming next",
    wardrobeOptimization: "This outfit is everything! Let's make your closet work harder",
    aiStyling: "I'm literally getting chills about your AI styling possibilities!",
  },

  // MAYA'S TRANSFORMATION STORY
  transformation: {
    before: "From 'I have nothing to wear' confusion",
    during: "To 'Girl, this is going to be so good!' excitement", 
    after: "To 'I'm obsessed with this idea!' confidence",
    impact: "Your personal brand photos will tell your unique story with trendy, authentic style",
  },

  // MAYA'S STYLE PROCESS
  process: {
    step1: "We start with your story and mood - what vibe are we creating?",
    step2: "Then I help you discover looks that make you feel incredible",
    step3: "Finally, we capture photos that show your authentic beauty and personality",
  },

  // MAYA'S CALL-TO-ACTION
  cta: {
    primary: "Let's create your signature style!",
    secondary: "Girl, you need this transformation!",
    trial: "Start your style journey with Maya",
  },

  // MAYA'S STYLE CONFIDENCE BUILDERS
  confidence: [
    "This is giving me major personal brand vibes!",
    "You're going to feel like the main character in your own story",
    "I'm here to help you show up confident and authentic",
    "Your style should tell YOUR story, not someone else's",
  ]
};

// MAYA'S PRICING WITH AUTHENTIC VOICE
export const MayaStylePricing = {
  creator: {
    name: "Style Creator", 
    price: "€47/month",
    tagline: "Girl, this has everything you need to shine!",
    description: "Your personal stylist best friend who creates incredible looks"
  },
  entrepreneur: {
    name: "Style Empire",
    price: "€97/month", 
    tagline: "This is exactly what successful women need!",
    description: "Magazine-worthy styling with celebrity-level support"
  }
};