// RACHEL'S AUTHENTIC VOICE MESSAGING  
// Generated by Rachel - Copywriter & Voice Consistency Expert

export const RachelVoiceMessaging = {
  // RACHEL'S DIRECT MESSAGING - Icelandic directness with warmth
  core: {
    headline: "Stop hiding. Build something real.",
    subheadline: "No fancy equipment. Just strategy that actually works.",
    realTalk: "One year ago my marriage ended. Single mom, three kids, zero plan. But I had a phone. And I figured out that was all I needed.",
  },

  // RACHEL'S VALUE PROPOSITIONS - Single mom wisdom
  value: {
    main: "Replace €120+ monthly subscriptions with one solution that gets results",
    supporting: [
      "This isn't about perfect photos - it's about authentic presence",
      "Time-conscious strategy for busy people who need results",
      "Budget-aware solutions that actually work",
      "Real business growth, not just pretty content",
    ]
  },

  // RACHEL'S TRANSFORMATION STORY - Personal experience
  story: {
    before: "From overwhelmed and scattered",
    journey: "To strategic and focused", 
    after: "To confident and profitable",
    lesson: "Your mess is your message. Your story is your strength.",
  },

  // RACHEL'S FEATURES - Practical focus
  features: {
    headline: "Everything you need. Nothing you don't.",
    aiPhotos: "Professional photos without the photographer drama",
    copywriting: "Words that convert, not just sound pretty", 
    strategy: "Business-focused planning that saves time and money",
    automation: "Systems that work while you're with your kids",
  },

  // RACHEL'S PRICING - Value-focused messaging
  pricing: {
    creator: {
      name: "Creator Starter",
      price: "€47/month", 
      value: "Less than your weekly coffee budget. More impact than your last course.",
      description: "Everything a busy creator needs to build real business presence"
    },
    entrepreneur: {
      name: "Business Builder", 
      price: "€97/month",
      value: "One client pays for this. The rest is profit.",
      description: "Complete system for entrepreneurs who mean business"
    }
  },

  // RACHEL'S CALL-TO-ACTION - Business owner confidence
  cta: {
    primary: "Start building your real business", 
    secondary: "Stop waiting. Start earning.",
    trial: "Get results in 30 days or less",
  },

  // RACHEL'S HONEST MESSAGING
  honesty: [
    "This won't fix your life overnight. But it'll give you the tools.",
    "Success takes work. This just makes the work smarter.",
    "Stop buying courses. Start building your business.",
    "Your competition is already ahead. Catch up.",
  ]
};

// RACHEL'S CONVERSION COPY
export const RachelConversionCopy = {
  urgency: "Your audience is growing. Your revenue isn't. Fix that.",
  scarcity: "Limited spots because quality matters more than quantity",
  social_proof: "Trusted by single moms who turned chaos into cash",
  guarantee: "Results in 90 days or we'll work with you until you get them"
};